/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.clientapi.pdm.models.AccessOpenidCreateAuthUrlRequest
import com.clientapi.pdm.models.AccessOpenidCreateAuthUrlResponse
import com.clientapi.pdm.models.AccessOpenidCreateLoginRequest
import com.clientapi.pdm.models.AccessOpenidCreateLoginResponse
import com.clientapi.pdm.models.AccessOpenidGetOpenidResponse
import com.clientapi.pdm.models.PdmError

import com.squareup.moshi.Json

import com.clientapi.pdm.infrastructure.ApiClient
import com.clientapi.pdm.infrastructure.ApiResponse
import com.clientapi.pdm.infrastructure.ClientException
import com.clientapi.pdm.infrastructure.ClientError
import com.clientapi.pdm.infrastructure.ServerException
import com.clientapi.pdm.infrastructure.ServerError
import com.clientapi.pdm.infrastructure.MultiValueMap
import com.clientapi.pdm.infrastructure.PartConfig
import com.clientapi.pdm.infrastructure.RequestConfig
import com.clientapi.pdm.infrastructure.RequestMethod
import com.clientapi.pdm.infrastructure.ResponseType
import com.clientapi.pdm.infrastructure.Success
import com.clientapi.pdm.infrastructure.toMultiValue

open class AccessOpenidApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8443/api2/json")
        }
    }

    /**
     * POST /access/openid/auth-url
     * Create OpenID Redirect Session
     * Create OpenID Redirect Session  Permissions: Anyone can access this (before the user is authenticated).
     * @param accessOpenidCreateAuthUrlRequest 
     * @return AccessOpenidCreateAuthUrlResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun accessOpenidCreateAuthUrl(accessOpenidCreateAuthUrlRequest: AccessOpenidCreateAuthUrlRequest) : AccessOpenidCreateAuthUrlResponse {
        val localVarResponse = accessOpenidCreateAuthUrlWithHttpInfo(accessOpenidCreateAuthUrlRequest = accessOpenidCreateAuthUrlRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AccessOpenidCreateAuthUrlResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /access/openid/auth-url
     * Create OpenID Redirect Session
     * Create OpenID Redirect Session  Permissions: Anyone can access this (before the user is authenticated).
     * @param accessOpenidCreateAuthUrlRequest 
     * @return ApiResponse<AccessOpenidCreateAuthUrlResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun accessOpenidCreateAuthUrlWithHttpInfo(accessOpenidCreateAuthUrlRequest: AccessOpenidCreateAuthUrlRequest) : ApiResponse<AccessOpenidCreateAuthUrlResponse?> {
        val localVariableConfig = accessOpenidCreateAuthUrlRequestConfig(accessOpenidCreateAuthUrlRequest = accessOpenidCreateAuthUrlRequest)

        return request<AccessOpenidCreateAuthUrlRequest, AccessOpenidCreateAuthUrlResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation accessOpenidCreateAuthUrl
     *
     * @param accessOpenidCreateAuthUrlRequest 
     * @return RequestConfig
     */
    fun accessOpenidCreateAuthUrlRequestConfig(accessOpenidCreateAuthUrlRequest: AccessOpenidCreateAuthUrlRequest) : RequestConfig<AccessOpenidCreateAuthUrlRequest> {
        val localVariableBody = accessOpenidCreateAuthUrlRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/access/openid/auth-url",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /access/openid/login
     * Get a new ticket as an HttpOnly cookie
     * Get a new ticket as an HttpOnly cookie. Supports tickets via cookies.
     * @param accessOpenidCreateLoginRequest 
     * @return AccessOpenidCreateLoginResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun accessOpenidCreateLogin(accessOpenidCreateLoginRequest: AccessOpenidCreateLoginRequest) : AccessOpenidCreateLoginResponse {
        val localVarResponse = accessOpenidCreateLoginWithHttpInfo(accessOpenidCreateLoginRequest = accessOpenidCreateLoginRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AccessOpenidCreateLoginResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /access/openid/login
     * Get a new ticket as an HttpOnly cookie
     * Get a new ticket as an HttpOnly cookie. Supports tickets via cookies.
     * @param accessOpenidCreateLoginRequest 
     * @return ApiResponse<AccessOpenidCreateLoginResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun accessOpenidCreateLoginWithHttpInfo(accessOpenidCreateLoginRequest: AccessOpenidCreateLoginRequest) : ApiResponse<AccessOpenidCreateLoginResponse?> {
        val localVariableConfig = accessOpenidCreateLoginRequestConfig(accessOpenidCreateLoginRequest = accessOpenidCreateLoginRequest)

        return request<AccessOpenidCreateLoginRequest, AccessOpenidCreateLoginResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation accessOpenidCreateLogin
     *
     * @param accessOpenidCreateLoginRequest 
     * @return RequestConfig
     */
    fun accessOpenidCreateLoginRequestConfig(accessOpenidCreateLoginRequest: AccessOpenidCreateLoginRequest) : RequestConfig<AccessOpenidCreateLoginRequest> {
        val localVariableBody = accessOpenidCreateLoginRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/access/openid/login",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * GET /access/openid
     * Directory index
     * Directory index.
     * @return AccessOpenidGetOpenidResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun accessOpenidGetOpenid() : AccessOpenidGetOpenidResponse {
        val localVarResponse = accessOpenidGetOpenidWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AccessOpenidGetOpenidResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /access/openid
     * Directory index
     * Directory index.
     * @return ApiResponse<AccessOpenidGetOpenidResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun accessOpenidGetOpenidWithHttpInfo() : ApiResponse<AccessOpenidGetOpenidResponse?> {
        val localVariableConfig = accessOpenidGetOpenidRequestConfig()

        return request<Unit, AccessOpenidGetOpenidResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation accessOpenidGetOpenid
     *
     * @return RequestConfig
     */
    fun accessOpenidGetOpenidRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/access/openid",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
