/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.clientapi.pdm.models.AccessDomainsCreateSyncRequest
import com.clientapi.pdm.models.AccessDomainsCreateSyncResponse
import com.clientapi.pdm.models.AccessDomainsGetDomainsResponse
import com.clientapi.pdm.models.PdmError

import com.squareup.moshi.Json

import com.clientapi.pdm.infrastructure.ApiClient
import com.clientapi.pdm.infrastructure.ApiResponse
import com.clientapi.pdm.infrastructure.ClientException
import com.clientapi.pdm.infrastructure.ClientError
import com.clientapi.pdm.infrastructure.ServerException
import com.clientapi.pdm.infrastructure.ServerError
import com.clientapi.pdm.infrastructure.MultiValueMap
import com.clientapi.pdm.infrastructure.PartConfig
import com.clientapi.pdm.infrastructure.RequestConfig
import com.clientapi.pdm.infrastructure.RequestMethod
import com.clientapi.pdm.infrastructure.ResponseType
import com.clientapi.pdm.infrastructure.Success
import com.clientapi.pdm.infrastructure.toMultiValue

open class AccessDomainsApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8443/api2/json")
        }
    }

    /**
     * POST /access/domains/{realm}/sync
     * Synchronize users of a given realm
     * Synchronize users of a given realm
     * @param realm Authentication domain ID
     * @param accessDomainsCreateSyncRequest  (optional)
     * @return AccessDomainsCreateSyncResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun accessDomainsCreateSync(realm: kotlin.String, accessDomainsCreateSyncRequest: AccessDomainsCreateSyncRequest? = null) : AccessDomainsCreateSyncResponse {
        val localVarResponse = accessDomainsCreateSyncWithHttpInfo(realm = realm, accessDomainsCreateSyncRequest = accessDomainsCreateSyncRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AccessDomainsCreateSyncResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /access/domains/{realm}/sync
     * Synchronize users of a given realm
     * Synchronize users of a given realm
     * @param realm Authentication domain ID
     * @param accessDomainsCreateSyncRequest  (optional)
     * @return ApiResponse<AccessDomainsCreateSyncResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun accessDomainsCreateSyncWithHttpInfo(realm: kotlin.String, accessDomainsCreateSyncRequest: AccessDomainsCreateSyncRequest?) : ApiResponse<AccessDomainsCreateSyncResponse?> {
        val localVariableConfig = accessDomainsCreateSyncRequestConfig(realm = realm, accessDomainsCreateSyncRequest = accessDomainsCreateSyncRequest)

        return request<AccessDomainsCreateSyncRequest, AccessDomainsCreateSyncResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation accessDomainsCreateSync
     *
     * @param realm Authentication domain ID
     * @param accessDomainsCreateSyncRequest  (optional)
     * @return RequestConfig
     */
    fun accessDomainsCreateSyncRequestConfig(realm: kotlin.String, accessDomainsCreateSyncRequest: AccessDomainsCreateSyncRequest?) : RequestConfig<AccessDomainsCreateSyncRequest> {
        val localVariableBody = accessDomainsCreateSyncRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/access/domains/{realm}/sync".replace("{"+"realm"+"}", encodeURIComponent(realm.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /access/domains
     * Authentication domain/realm index
     * Authentication domain/realm index.  Permissions: Anyone can access this, because we need that list for the login box (before the user is authenticated).
     * @return AccessDomainsGetDomainsResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun accessDomainsGetDomains() : AccessDomainsGetDomainsResponse {
        val localVarResponse = accessDomainsGetDomainsWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AccessDomainsGetDomainsResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /access/domains
     * Authentication domain/realm index
     * Authentication domain/realm index.  Permissions: Anyone can access this, because we need that list for the login box (before the user is authenticated).
     * @return ApiResponse<AccessDomainsGetDomainsResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun accessDomainsGetDomainsWithHttpInfo() : ApiResponse<AccessDomainsGetDomainsResponse?> {
        val localVariableConfig = accessDomainsGetDomainsRequestConfig()

        return request<Unit, AccessDomainsGetDomainsResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation accessDomainsGetDomains
     *
     * @return RequestConfig
     */
    fun accessDomainsGetDomainsRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/access/domains",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
