/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.clientapi.pdm.models.AccessTfaCreateTfaRequest
import com.clientapi.pdm.models.AccessTfaCreateTfaResponse
import com.clientapi.pdm.models.AccessTfaDeleteTfaResponse
import com.clientapi.pdm.models.AccessTfaGetAccessTfaByUseridByIdResponse
import com.clientapi.pdm.models.AccessTfaGetAccessTfaByUseridResponse
import com.clientapi.pdm.models.AccessTfaGetTfaResponse
import com.clientapi.pdm.models.AccessTfaUpdateTfaRequest
import com.clientapi.pdm.models.AccessTfaUpdateTfaResponse
import com.clientapi.pdm.models.PdmError

import com.squareup.moshi.Json

import com.clientapi.pdm.infrastructure.ApiClient
import com.clientapi.pdm.infrastructure.ApiResponse
import com.clientapi.pdm.infrastructure.ClientException
import com.clientapi.pdm.infrastructure.ClientError
import com.clientapi.pdm.infrastructure.ServerException
import com.clientapi.pdm.infrastructure.ServerError
import com.clientapi.pdm.infrastructure.MultiValueMap
import com.clientapi.pdm.infrastructure.PartConfig
import com.clientapi.pdm.infrastructure.RequestConfig
import com.clientapi.pdm.infrastructure.RequestMethod
import com.clientapi.pdm.infrastructure.ResponseType
import com.clientapi.pdm.infrastructure.Success
import com.clientapi.pdm.infrastructure.toMultiValue

open class AccessTfaApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8443/api2/json")
        }
    }

    /**
     * POST /access/tfa/{userid}
     * Add a TFA entry to the user
     * Add a TFA entry to the user.
     * @param userid User ID
     * @param accessTfaCreateTfaRequest 
     * @return AccessTfaCreateTfaResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun accessTfaCreateTfa(userid: kotlin.String, accessTfaCreateTfaRequest: AccessTfaCreateTfaRequest) : AccessTfaCreateTfaResponse {
        val localVarResponse = accessTfaCreateTfaWithHttpInfo(userid = userid, accessTfaCreateTfaRequest = accessTfaCreateTfaRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AccessTfaCreateTfaResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /access/tfa/{userid}
     * Add a TFA entry to the user
     * Add a TFA entry to the user.
     * @param userid User ID
     * @param accessTfaCreateTfaRequest 
     * @return ApiResponse<AccessTfaCreateTfaResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun accessTfaCreateTfaWithHttpInfo(userid: kotlin.String, accessTfaCreateTfaRequest: AccessTfaCreateTfaRequest) : ApiResponse<AccessTfaCreateTfaResponse?> {
        val localVariableConfig = accessTfaCreateTfaRequestConfig(userid = userid, accessTfaCreateTfaRequest = accessTfaCreateTfaRequest)

        return request<AccessTfaCreateTfaRequest, AccessTfaCreateTfaResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation accessTfaCreateTfa
     *
     * @param userid User ID
     * @param accessTfaCreateTfaRequest 
     * @return RequestConfig
     */
    fun accessTfaCreateTfaRequestConfig(userid: kotlin.String, accessTfaCreateTfaRequest: AccessTfaCreateTfaRequest) : RequestConfig<AccessTfaCreateTfaRequest> {
        val localVariableBody = accessTfaCreateTfaRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/access/tfa/{userid}".replace("{"+"userid"+"}", encodeURIComponent(userid.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /access/tfa/{userid}/{id}
     * Delete a single TFA entry
     * Delete a single TFA entry.
     * @param id the tfa entry id
     * @param userid User ID
     * @param password Password. (optional)
     * @return AccessTfaDeleteTfaResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun accessTfaDeleteTfa(id: kotlin.String, userid: kotlin.String, password: kotlin.String? = null) : AccessTfaDeleteTfaResponse {
        val localVarResponse = accessTfaDeleteTfaWithHttpInfo(id = id, userid = userid, password = password)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AccessTfaDeleteTfaResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /access/tfa/{userid}/{id}
     * Delete a single TFA entry
     * Delete a single TFA entry.
     * @param id the tfa entry id
     * @param userid User ID
     * @param password Password. (optional)
     * @return ApiResponse<AccessTfaDeleteTfaResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun accessTfaDeleteTfaWithHttpInfo(id: kotlin.String, userid: kotlin.String, password: kotlin.String?) : ApiResponse<AccessTfaDeleteTfaResponse?> {
        val localVariableConfig = accessTfaDeleteTfaRequestConfig(id = id, userid = userid, password = password)

        return request<Unit, AccessTfaDeleteTfaResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation accessTfaDeleteTfa
     *
     * @param id the tfa entry id
     * @param userid User ID
     * @param password Password. (optional)
     * @return RequestConfig
     */
    fun accessTfaDeleteTfaRequestConfig(id: kotlin.String, userid: kotlin.String, password: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (password != null) {
                    put("password", listOf(password.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/access/tfa/{userid}/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())).replace("{"+"userid"+"}", encodeURIComponent(userid.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /access/tfa/{userid}
     * Add a TOTP secret to the user
     * Add a TOTP secret to the user.
     * @param userid User ID
     * @return AccessTfaGetAccessTfaByUseridResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun accessTfaGetAccessTfaByUserid(userid: kotlin.String) : AccessTfaGetAccessTfaByUseridResponse {
        val localVarResponse = accessTfaGetAccessTfaByUseridWithHttpInfo(userid = userid)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AccessTfaGetAccessTfaByUseridResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /access/tfa/{userid}
     * Add a TOTP secret to the user
     * Add a TOTP secret to the user.
     * @param userid User ID
     * @return ApiResponse<AccessTfaGetAccessTfaByUseridResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun accessTfaGetAccessTfaByUseridWithHttpInfo(userid: kotlin.String) : ApiResponse<AccessTfaGetAccessTfaByUseridResponse?> {
        val localVariableConfig = accessTfaGetAccessTfaByUseridRequestConfig(userid = userid)

        return request<Unit, AccessTfaGetAccessTfaByUseridResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation accessTfaGetAccessTfaByUserid
     *
     * @param userid User ID
     * @return RequestConfig
     */
    fun accessTfaGetAccessTfaByUseridRequestConfig(userid: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/access/tfa/{userid}".replace("{"+"userid"+"}", encodeURIComponent(userid.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /access/tfa/{userid}/{id}
     * Get a single TFA entry
     * Get a single TFA entry.
     * @param id the tfa entry id
     * @param userid User ID
     * @return AccessTfaGetAccessTfaByUseridByIdResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun accessTfaGetAccessTfaByUseridById(id: kotlin.String, userid: kotlin.String) : AccessTfaGetAccessTfaByUseridByIdResponse {
        val localVarResponse = accessTfaGetAccessTfaByUseridByIdWithHttpInfo(id = id, userid = userid)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AccessTfaGetAccessTfaByUseridByIdResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /access/tfa/{userid}/{id}
     * Get a single TFA entry
     * Get a single TFA entry.
     * @param id the tfa entry id
     * @param userid User ID
     * @return ApiResponse<AccessTfaGetAccessTfaByUseridByIdResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun accessTfaGetAccessTfaByUseridByIdWithHttpInfo(id: kotlin.String, userid: kotlin.String) : ApiResponse<AccessTfaGetAccessTfaByUseridByIdResponse?> {
        val localVariableConfig = accessTfaGetAccessTfaByUseridByIdRequestConfig(id = id, userid = userid)

        return request<Unit, AccessTfaGetAccessTfaByUseridByIdResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation accessTfaGetAccessTfaByUseridById
     *
     * @param id the tfa entry id
     * @param userid User ID
     * @return RequestConfig
     */
    fun accessTfaGetAccessTfaByUseridByIdRequestConfig(id: kotlin.String, userid: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/access/tfa/{userid}/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())).replace("{"+"userid"+"}", encodeURIComponent(userid.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /access/tfa
     * List user TFA configuration
     * List user TFA configuration.  Permissions: Returns all or just the logged-in user, depending on privileges.
     * @return AccessTfaGetTfaResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun accessTfaGetTfa() : AccessTfaGetTfaResponse {
        val localVarResponse = accessTfaGetTfaWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AccessTfaGetTfaResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /access/tfa
     * List user TFA configuration
     * List user TFA configuration.  Permissions: Returns all or just the logged-in user, depending on privileges.
     * @return ApiResponse<AccessTfaGetTfaResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun accessTfaGetTfaWithHttpInfo() : ApiResponse<AccessTfaGetTfaResponse?> {
        val localVariableConfig = accessTfaGetTfaRequestConfig()

        return request<Unit, AccessTfaGetTfaResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation accessTfaGetTfa
     *
     * @return RequestConfig
     */
    fun accessTfaGetTfaRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/access/tfa",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /access/tfa/{userid}/{id}
     * Update user&#39;s TFA entry description
     * Update user&#39;s TFA entry description.
     * @param id the tfa entry id
     * @param userid User ID
     * @param accessTfaUpdateTfaRequest  (optional)
     * @return AccessTfaUpdateTfaResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun accessTfaUpdateTfa(id: kotlin.String, userid: kotlin.String, accessTfaUpdateTfaRequest: AccessTfaUpdateTfaRequest? = null) : AccessTfaUpdateTfaResponse {
        val localVarResponse = accessTfaUpdateTfaWithHttpInfo(id = id, userid = userid, accessTfaUpdateTfaRequest = accessTfaUpdateTfaRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AccessTfaUpdateTfaResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /access/tfa/{userid}/{id}
     * Update user&#39;s TFA entry description
     * Update user&#39;s TFA entry description.
     * @param id the tfa entry id
     * @param userid User ID
     * @param accessTfaUpdateTfaRequest  (optional)
     * @return ApiResponse<AccessTfaUpdateTfaResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun accessTfaUpdateTfaWithHttpInfo(id: kotlin.String, userid: kotlin.String, accessTfaUpdateTfaRequest: AccessTfaUpdateTfaRequest?) : ApiResponse<AccessTfaUpdateTfaResponse?> {
        val localVariableConfig = accessTfaUpdateTfaRequestConfig(id = id, userid = userid, accessTfaUpdateTfaRequest = accessTfaUpdateTfaRequest)

        return request<AccessTfaUpdateTfaRequest, AccessTfaUpdateTfaResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation accessTfaUpdateTfa
     *
     * @param id the tfa entry id
     * @param userid User ID
     * @param accessTfaUpdateTfaRequest  (optional)
     * @return RequestConfig
     */
    fun accessTfaUpdateTfaRequestConfig(id: kotlin.String, userid: kotlin.String, accessTfaUpdateTfaRequest: AccessTfaUpdateTfaRequest?) : RequestConfig<AccessTfaUpdateTfaRequest> {
        val localVariableBody = accessTfaUpdateTfaRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/access/tfa/{userid}/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())).replace("{"+"userid"+"}", encodeURIComponent(userid.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
