/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.clientapi.pdm.models.AccessUsersCreateTokenRequest
import com.clientapi.pdm.models.AccessUsersCreateTokenResponse
import com.clientapi.pdm.models.AccessUsersCreateUsersRequest
import com.clientapi.pdm.models.AccessUsersCreateUsersResponse
import com.clientapi.pdm.models.AccessUsersDeleteTokenResponse
import com.clientapi.pdm.models.AccessUsersDeleteUsersResponse
import com.clientapi.pdm.models.AccessUsersGetAccessUsersByUseridResponse
import com.clientapi.pdm.models.AccessUsersGetAccessUsersByUseridTokenByTokenNameResponse
import com.clientapi.pdm.models.AccessUsersGetTokenResponse
import com.clientapi.pdm.models.AccessUsersGetUsersResponse
import com.clientapi.pdm.models.AccessUsersUpdateTokenRequest
import com.clientapi.pdm.models.AccessUsersUpdateTokenResponse
import com.clientapi.pdm.models.AccessUsersUpdateUsersRequest
import com.clientapi.pdm.models.AccessUsersUpdateUsersResponse
import com.clientapi.pdm.models.PdmError

import com.squareup.moshi.Json

import com.clientapi.pdm.infrastructure.ApiClient
import com.clientapi.pdm.infrastructure.ApiResponse
import com.clientapi.pdm.infrastructure.ClientException
import com.clientapi.pdm.infrastructure.ClientError
import com.clientapi.pdm.infrastructure.ServerException
import com.clientapi.pdm.infrastructure.ServerError
import com.clientapi.pdm.infrastructure.MultiValueMap
import com.clientapi.pdm.infrastructure.PartConfig
import com.clientapi.pdm.infrastructure.RequestConfig
import com.clientapi.pdm.infrastructure.RequestMethod
import com.clientapi.pdm.infrastructure.ResponseType
import com.clientapi.pdm.infrastructure.Success
import com.clientapi.pdm.infrastructure.toMultiValue

open class AccessUsersApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8443/api2/json")
        }
    }

    /**
     * POST /access/users/{userid}/token/{token-name}
     * Generate a new API token with given metadata
     * Generate a new API token with given metadata
     * @param tokenName The token ID part of an API token authentication id.  This alone does NOT uniquely identify the API token - use a full &#x60;Authid&#x60; for such use cases.
     * @param userid User ID
     * @param accessUsersCreateTokenRequest  (optional)
     * @return AccessUsersCreateTokenResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun accessUsersCreateToken(tokenName: kotlin.String, userid: kotlin.String, accessUsersCreateTokenRequest: AccessUsersCreateTokenRequest? = null) : AccessUsersCreateTokenResponse {
        val localVarResponse = accessUsersCreateTokenWithHttpInfo(tokenName = tokenName, userid = userid, accessUsersCreateTokenRequest = accessUsersCreateTokenRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AccessUsersCreateTokenResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /access/users/{userid}/token/{token-name}
     * Generate a new API token with given metadata
     * Generate a new API token with given metadata
     * @param tokenName The token ID part of an API token authentication id.  This alone does NOT uniquely identify the API token - use a full &#x60;Authid&#x60; for such use cases.
     * @param userid User ID
     * @param accessUsersCreateTokenRequest  (optional)
     * @return ApiResponse<AccessUsersCreateTokenResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun accessUsersCreateTokenWithHttpInfo(tokenName: kotlin.String, userid: kotlin.String, accessUsersCreateTokenRequest: AccessUsersCreateTokenRequest?) : ApiResponse<AccessUsersCreateTokenResponse?> {
        val localVariableConfig = accessUsersCreateTokenRequestConfig(tokenName = tokenName, userid = userid, accessUsersCreateTokenRequest = accessUsersCreateTokenRequest)

        return request<AccessUsersCreateTokenRequest, AccessUsersCreateTokenResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation accessUsersCreateToken
     *
     * @param tokenName The token ID part of an API token authentication id.  This alone does NOT uniquely identify the API token - use a full &#x60;Authid&#x60; for such use cases.
     * @param userid User ID
     * @param accessUsersCreateTokenRequest  (optional)
     * @return RequestConfig
     */
    fun accessUsersCreateTokenRequestConfig(tokenName: kotlin.String, userid: kotlin.String, accessUsersCreateTokenRequest: AccessUsersCreateTokenRequest?) : RequestConfig<AccessUsersCreateTokenRequest> {
        val localVariableBody = accessUsersCreateTokenRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/access/users/{userid}/token/{token-name}".replace("{"+"token-name"+"}", encodeURIComponent(tokenName.toString())).replace("{"+"userid"+"}", encodeURIComponent(userid.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /access/users
     * Create new user
     * Create new user.
     * @param accessUsersCreateUsersRequest 
     * @return AccessUsersCreateUsersResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun accessUsersCreateUsers(accessUsersCreateUsersRequest: AccessUsersCreateUsersRequest) : AccessUsersCreateUsersResponse {
        val localVarResponse = accessUsersCreateUsersWithHttpInfo(accessUsersCreateUsersRequest = accessUsersCreateUsersRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AccessUsersCreateUsersResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /access/users
     * Create new user
     * Create new user.
     * @param accessUsersCreateUsersRequest 
     * @return ApiResponse<AccessUsersCreateUsersResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun accessUsersCreateUsersWithHttpInfo(accessUsersCreateUsersRequest: AccessUsersCreateUsersRequest) : ApiResponse<AccessUsersCreateUsersResponse?> {
        val localVariableConfig = accessUsersCreateUsersRequestConfig(accessUsersCreateUsersRequest = accessUsersCreateUsersRequest)

        return request<AccessUsersCreateUsersRequest, AccessUsersCreateUsersResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation accessUsersCreateUsers
     *
     * @param accessUsersCreateUsersRequest 
     * @return RequestConfig
     */
    fun accessUsersCreateUsersRequestConfig(accessUsersCreateUsersRequest: AccessUsersCreateUsersRequest) : RequestConfig<AccessUsersCreateUsersRequest> {
        val localVariableBody = accessUsersCreateUsersRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/access/users",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /access/users/{userid}/token/{token-name}
     * Delete a user&#39;s API token
     * Delete a user&#39;s API token
     * @param tokenName The token ID part of an API token authentication id.  This alone does NOT uniquely identify the API token - use a full &#x60;Authid&#x60; for such use cases.
     * @param userid User ID
     * @param digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications. (optional)
     * @return AccessUsersDeleteTokenResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun accessUsersDeleteToken(tokenName: kotlin.String, userid: kotlin.String, digest: kotlin.String? = null) : AccessUsersDeleteTokenResponse {
        val localVarResponse = accessUsersDeleteTokenWithHttpInfo(tokenName = tokenName, userid = userid, digest = digest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AccessUsersDeleteTokenResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /access/users/{userid}/token/{token-name}
     * Delete a user&#39;s API token
     * Delete a user&#39;s API token
     * @param tokenName The token ID part of an API token authentication id.  This alone does NOT uniquely identify the API token - use a full &#x60;Authid&#x60; for such use cases.
     * @param userid User ID
     * @param digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications. (optional)
     * @return ApiResponse<AccessUsersDeleteTokenResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun accessUsersDeleteTokenWithHttpInfo(tokenName: kotlin.String, userid: kotlin.String, digest: kotlin.String?) : ApiResponse<AccessUsersDeleteTokenResponse?> {
        val localVariableConfig = accessUsersDeleteTokenRequestConfig(tokenName = tokenName, userid = userid, digest = digest)

        return request<Unit, AccessUsersDeleteTokenResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation accessUsersDeleteToken
     *
     * @param tokenName The token ID part of an API token authentication id.  This alone does NOT uniquely identify the API token - use a full &#x60;Authid&#x60; for such use cases.
     * @param userid User ID
     * @param digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications. (optional)
     * @return RequestConfig
     */
    fun accessUsersDeleteTokenRequestConfig(tokenName: kotlin.String, userid: kotlin.String, digest: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (digest != null) {
                    put("digest", listOf(digest.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/access/users/{userid}/token/{token-name}".replace("{"+"token-name"+"}", encodeURIComponent(tokenName.toString())).replace("{"+"userid"+"}", encodeURIComponent(userid.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /access/users/{userid}
     * Remove a user from the configuration file
     * Remove a user from the configuration file.
     * @param userid User ID
     * @param digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications. (optional)
     * @return AccessUsersDeleteUsersResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun accessUsersDeleteUsers(userid: kotlin.String, digest: kotlin.String? = null) : AccessUsersDeleteUsersResponse {
        val localVarResponse = accessUsersDeleteUsersWithHttpInfo(userid = userid, digest = digest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AccessUsersDeleteUsersResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /access/users/{userid}
     * Remove a user from the configuration file
     * Remove a user from the configuration file.
     * @param userid User ID
     * @param digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications. (optional)
     * @return ApiResponse<AccessUsersDeleteUsersResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun accessUsersDeleteUsersWithHttpInfo(userid: kotlin.String, digest: kotlin.String?) : ApiResponse<AccessUsersDeleteUsersResponse?> {
        val localVariableConfig = accessUsersDeleteUsersRequestConfig(userid = userid, digest = digest)

        return request<Unit, AccessUsersDeleteUsersResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation accessUsersDeleteUsers
     *
     * @param userid User ID
     * @param digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications. (optional)
     * @return RequestConfig
     */
    fun accessUsersDeleteUsersRequestConfig(userid: kotlin.String, digest: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (digest != null) {
                    put("digest", listOf(digest.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/access/users/{userid}".replace("{"+"userid"+"}", encodeURIComponent(userid.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /access/users/{userid}
     * Read user configuration data
     * Read user configuration data.
     * @param userid User ID
     * @return AccessUsersGetAccessUsersByUseridResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun accessUsersGetAccessUsersByUserid(userid: kotlin.String) : AccessUsersGetAccessUsersByUseridResponse {
        val localVarResponse = accessUsersGetAccessUsersByUseridWithHttpInfo(userid = userid)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AccessUsersGetAccessUsersByUseridResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /access/users/{userid}
     * Read user configuration data
     * Read user configuration data.
     * @param userid User ID
     * @return ApiResponse<AccessUsersGetAccessUsersByUseridResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun accessUsersGetAccessUsersByUseridWithHttpInfo(userid: kotlin.String) : ApiResponse<AccessUsersGetAccessUsersByUseridResponse?> {
        val localVariableConfig = accessUsersGetAccessUsersByUseridRequestConfig(userid = userid)

        return request<Unit, AccessUsersGetAccessUsersByUseridResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation accessUsersGetAccessUsersByUserid
     *
     * @param userid User ID
     * @return RequestConfig
     */
    fun accessUsersGetAccessUsersByUseridRequestConfig(userid: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/access/users/{userid}".replace("{"+"userid"+"}", encodeURIComponent(userid.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /access/users/{userid}/token/{token-name}
     * Read user&#39;s API token metadata
     * Read user&#39;s API token metadata
     * @param tokenName The token ID part of an API token authentication id.  This alone does NOT uniquely identify the API token - use a full &#x60;Authid&#x60; for such use cases.
     * @param userid User ID
     * @return AccessUsersGetAccessUsersByUseridTokenByTokenNameResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun accessUsersGetAccessUsersByUseridTokenByTokenName(tokenName: kotlin.String, userid: kotlin.String) : AccessUsersGetAccessUsersByUseridTokenByTokenNameResponse {
        val localVarResponse = accessUsersGetAccessUsersByUseridTokenByTokenNameWithHttpInfo(tokenName = tokenName, userid = userid)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AccessUsersGetAccessUsersByUseridTokenByTokenNameResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /access/users/{userid}/token/{token-name}
     * Read user&#39;s API token metadata
     * Read user&#39;s API token metadata
     * @param tokenName The token ID part of an API token authentication id.  This alone does NOT uniquely identify the API token - use a full &#x60;Authid&#x60; for such use cases.
     * @param userid User ID
     * @return ApiResponse<AccessUsersGetAccessUsersByUseridTokenByTokenNameResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun accessUsersGetAccessUsersByUseridTokenByTokenNameWithHttpInfo(tokenName: kotlin.String, userid: kotlin.String) : ApiResponse<AccessUsersGetAccessUsersByUseridTokenByTokenNameResponse?> {
        val localVariableConfig = accessUsersGetAccessUsersByUseridTokenByTokenNameRequestConfig(tokenName = tokenName, userid = userid)

        return request<Unit, AccessUsersGetAccessUsersByUseridTokenByTokenNameResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation accessUsersGetAccessUsersByUseridTokenByTokenName
     *
     * @param tokenName The token ID part of an API token authentication id.  This alone does NOT uniquely identify the API token - use a full &#x60;Authid&#x60; for such use cases.
     * @param userid User ID
     * @return RequestConfig
     */
    fun accessUsersGetAccessUsersByUseridTokenByTokenNameRequestConfig(tokenName: kotlin.String, userid: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/access/users/{userid}/token/{token-name}".replace("{"+"token-name"+"}", encodeURIComponent(tokenName.toString())).replace("{"+"userid"+"}", encodeURIComponent(userid.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /access/users/{userid}/token
     * List user&#39;s API tokens
     * List user&#39;s API tokens
     * @param userid User ID
     * @return AccessUsersGetTokenResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun accessUsersGetToken(userid: kotlin.String) : AccessUsersGetTokenResponse {
        val localVarResponse = accessUsersGetTokenWithHttpInfo(userid = userid)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AccessUsersGetTokenResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /access/users/{userid}/token
     * List user&#39;s API tokens
     * List user&#39;s API tokens
     * @param userid User ID
     * @return ApiResponse<AccessUsersGetTokenResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun accessUsersGetTokenWithHttpInfo(userid: kotlin.String) : ApiResponse<AccessUsersGetTokenResponse?> {
        val localVariableConfig = accessUsersGetTokenRequestConfig(userid = userid)

        return request<Unit, AccessUsersGetTokenResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation accessUsersGetToken
     *
     * @param userid User ID
     * @return RequestConfig
     */
    fun accessUsersGetTokenRequestConfig(userid: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/access/users/{userid}/token".replace("{"+"userid"+"}", encodeURIComponent(userid.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /access/users
     * List users
     * List users  Permissions: Returns all or just the logged-in user (/API token owner), depending on privileges.
     * @param includeTokens Include user&#39;s API tokens in returned list. (optional, default to false)
     * @return AccessUsersGetUsersResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun accessUsersGetUsers(includeTokens: kotlin.Boolean? = false) : AccessUsersGetUsersResponse {
        val localVarResponse = accessUsersGetUsersWithHttpInfo(includeTokens = includeTokens)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AccessUsersGetUsersResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /access/users
     * List users
     * List users  Permissions: Returns all or just the logged-in user (/API token owner), depending on privileges.
     * @param includeTokens Include user&#39;s API tokens in returned list. (optional, default to false)
     * @return ApiResponse<AccessUsersGetUsersResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun accessUsersGetUsersWithHttpInfo(includeTokens: kotlin.Boolean?) : ApiResponse<AccessUsersGetUsersResponse?> {
        val localVariableConfig = accessUsersGetUsersRequestConfig(includeTokens = includeTokens)

        return request<Unit, AccessUsersGetUsersResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation accessUsersGetUsers
     *
     * @param includeTokens Include user&#39;s API tokens in returned list. (optional, default to false)
     * @return RequestConfig
     */
    fun accessUsersGetUsersRequestConfig(includeTokens: kotlin.Boolean?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (includeTokens != null) {
                    put("include_tokens", listOf(includeTokens.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/access/users",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /access/users/{userid}/token/{token-name}
     * Update user&#39;s API token metadata
     * Update user&#39;s API token metadata. If regenerate is set to true, the token and it&#39;s new secret will be returned.
     * @param tokenName The token ID part of an API token authentication id.  This alone does NOT uniquely identify the API token - use a full &#x60;Authid&#x60; for such use cases.
     * @param userid User ID
     * @param accessUsersUpdateTokenRequest  (optional)
     * @return AccessUsersUpdateTokenResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun accessUsersUpdateToken(tokenName: kotlin.String, userid: kotlin.String, accessUsersUpdateTokenRequest: AccessUsersUpdateTokenRequest? = null) : AccessUsersUpdateTokenResponse {
        val localVarResponse = accessUsersUpdateTokenWithHttpInfo(tokenName = tokenName, userid = userid, accessUsersUpdateTokenRequest = accessUsersUpdateTokenRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AccessUsersUpdateTokenResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /access/users/{userid}/token/{token-name}
     * Update user&#39;s API token metadata
     * Update user&#39;s API token metadata. If regenerate is set to true, the token and it&#39;s new secret will be returned.
     * @param tokenName The token ID part of an API token authentication id.  This alone does NOT uniquely identify the API token - use a full &#x60;Authid&#x60; for such use cases.
     * @param userid User ID
     * @param accessUsersUpdateTokenRequest  (optional)
     * @return ApiResponse<AccessUsersUpdateTokenResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun accessUsersUpdateTokenWithHttpInfo(tokenName: kotlin.String, userid: kotlin.String, accessUsersUpdateTokenRequest: AccessUsersUpdateTokenRequest?) : ApiResponse<AccessUsersUpdateTokenResponse?> {
        val localVariableConfig = accessUsersUpdateTokenRequestConfig(tokenName = tokenName, userid = userid, accessUsersUpdateTokenRequest = accessUsersUpdateTokenRequest)

        return request<AccessUsersUpdateTokenRequest, AccessUsersUpdateTokenResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation accessUsersUpdateToken
     *
     * @param tokenName The token ID part of an API token authentication id.  This alone does NOT uniquely identify the API token - use a full &#x60;Authid&#x60; for such use cases.
     * @param userid User ID
     * @param accessUsersUpdateTokenRequest  (optional)
     * @return RequestConfig
     */
    fun accessUsersUpdateTokenRequestConfig(tokenName: kotlin.String, userid: kotlin.String, accessUsersUpdateTokenRequest: AccessUsersUpdateTokenRequest?) : RequestConfig<AccessUsersUpdateTokenRequest> {
        val localVariableBody = accessUsersUpdateTokenRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/access/users/{userid}/token/{token-name}".replace("{"+"token-name"+"}", encodeURIComponent(tokenName.toString())).replace("{"+"userid"+"}", encodeURIComponent(userid.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /access/users/{userid}
     * Update user configuration
     * Update user configuration.
     * @param userid User ID
     * @param accessUsersUpdateUsersRequest  (optional)
     * @return AccessUsersUpdateUsersResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun accessUsersUpdateUsers(userid: kotlin.String, accessUsersUpdateUsersRequest: AccessUsersUpdateUsersRequest? = null) : AccessUsersUpdateUsersResponse {
        val localVarResponse = accessUsersUpdateUsersWithHttpInfo(userid = userid, accessUsersUpdateUsersRequest = accessUsersUpdateUsersRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AccessUsersUpdateUsersResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /access/users/{userid}
     * Update user configuration
     * Update user configuration.
     * @param userid User ID
     * @param accessUsersUpdateUsersRequest  (optional)
     * @return ApiResponse<AccessUsersUpdateUsersResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun accessUsersUpdateUsersWithHttpInfo(userid: kotlin.String, accessUsersUpdateUsersRequest: AccessUsersUpdateUsersRequest?) : ApiResponse<AccessUsersUpdateUsersResponse?> {
        val localVariableConfig = accessUsersUpdateUsersRequestConfig(userid = userid, accessUsersUpdateUsersRequest = accessUsersUpdateUsersRequest)

        return request<AccessUsersUpdateUsersRequest, AccessUsersUpdateUsersResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation accessUsersUpdateUsers
     *
     * @param userid User ID
     * @param accessUsersUpdateUsersRequest  (optional)
     * @return RequestConfig
     */
    fun accessUsersUpdateUsersRequestConfig(userid: kotlin.String, accessUsersUpdateUsersRequest: AccessUsersUpdateUsersRequest?) : RequestConfig<AccessUsersUpdateUsersRequest> {
        val localVariableBody = accessUsersUpdateUsersRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/access/users/{userid}".replace("{"+"userid"+"}", encodeURIComponent(userid.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
