/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.clientapi.pdm.models.ConfigCertificateGetCertificateResponse
import com.clientapi.pdm.models.ConfigCertificateUpdateCertificateRequest
import com.clientapi.pdm.models.ConfigCertificateUpdateCertificateResponse
import com.clientapi.pdm.models.PdmError

import com.squareup.moshi.Json

import com.clientapi.pdm.infrastructure.ApiClient
import com.clientapi.pdm.infrastructure.ApiResponse
import com.clientapi.pdm.infrastructure.ClientException
import com.clientapi.pdm.infrastructure.ClientError
import com.clientapi.pdm.infrastructure.ServerException
import com.clientapi.pdm.infrastructure.ServerError
import com.clientapi.pdm.infrastructure.MultiValueMap
import com.clientapi.pdm.infrastructure.PartConfig
import com.clientapi.pdm.infrastructure.RequestConfig
import com.clientapi.pdm.infrastructure.RequestMethod
import com.clientapi.pdm.infrastructure.ResponseType
import com.clientapi.pdm.infrastructure.Success
import com.clientapi.pdm.infrastructure.toMultiValue

open class ConfigCertificateApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8443/api2/json")
        }
    }

    /**
     * GET /config/certificate
     * Get the node configuration
     * Get the node configuration
     * @return ConfigCertificateGetCertificateResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configCertificateGetCertificate() : ConfigCertificateGetCertificateResponse {
        val localVarResponse = configCertificateGetCertificateWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigCertificateGetCertificateResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /config/certificate
     * Get the node configuration
     * Get the node configuration
     * @return ApiResponse<ConfigCertificateGetCertificateResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configCertificateGetCertificateWithHttpInfo() : ApiResponse<ConfigCertificateGetCertificateResponse?> {
        val localVariableConfig = configCertificateGetCertificateRequestConfig()

        return request<Unit, ConfigCertificateGetCertificateResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configCertificateGetCertificate
     *
     * @return RequestConfig
     */
    fun configCertificateGetCertificateRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/config/certificate",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /config/certificate
     * Update the node configuration
     * Update the node configuration
     * @param configCertificateUpdateCertificateRequest  (optional)
     * @return ConfigCertificateUpdateCertificateResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configCertificateUpdateCertificate(configCertificateUpdateCertificateRequest: ConfigCertificateUpdateCertificateRequest? = null) : ConfigCertificateUpdateCertificateResponse {
        val localVarResponse = configCertificateUpdateCertificateWithHttpInfo(configCertificateUpdateCertificateRequest = configCertificateUpdateCertificateRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigCertificateUpdateCertificateResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /config/certificate
     * Update the node configuration
     * Update the node configuration
     * @param configCertificateUpdateCertificateRequest  (optional)
     * @return ApiResponse<ConfigCertificateUpdateCertificateResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configCertificateUpdateCertificateWithHttpInfo(configCertificateUpdateCertificateRequest: ConfigCertificateUpdateCertificateRequest?) : ApiResponse<ConfigCertificateUpdateCertificateResponse?> {
        val localVariableConfig = configCertificateUpdateCertificateRequestConfig(configCertificateUpdateCertificateRequest = configCertificateUpdateCertificateRequest)

        return request<ConfigCertificateUpdateCertificateRequest, ConfigCertificateUpdateCertificateResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configCertificateUpdateCertificate
     *
     * @param configCertificateUpdateCertificateRequest  (optional)
     * @return RequestConfig
     */
    fun configCertificateUpdateCertificateRequestConfig(configCertificateUpdateCertificateRequest: ConfigCertificateUpdateCertificateRequest?) : RequestConfig<ConfigCertificateUpdateCertificateRequest> {
        val localVariableBody = configCertificateUpdateCertificateRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/config/certificate",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
