/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.clientapi.pdm.models.NodesCreateTermproxyRequest
import com.clientapi.pdm.models.NodesCreateTermproxyResponse
import com.clientapi.pdm.models.NodesGetJournalResponse
import com.clientapi.pdm.models.NodesGetNodesByNodeResponse
import com.clientapi.pdm.models.NodesGetNodesResponse
import com.clientapi.pdm.models.NodesGetReportResponse
import com.clientapi.pdm.models.NodesGetRrdataResponse
import com.clientapi.pdm.models.NodesGetSyslogResponse
import com.clientapi.pdm.models.NodesGetVncwebsocketResponse
import com.clientapi.pdm.models.PdmCfEnum
import com.clientapi.pdm.models.PdmError
import com.clientapi.pdm.models.PdmTimeframeEnum

import com.squareup.moshi.Json

import com.clientapi.pdm.infrastructure.ApiClient
import com.clientapi.pdm.infrastructure.ApiResponse
import com.clientapi.pdm.infrastructure.ClientException
import com.clientapi.pdm.infrastructure.ClientError
import com.clientapi.pdm.infrastructure.ServerException
import com.clientapi.pdm.infrastructure.ServerError
import com.clientapi.pdm.infrastructure.MultiValueMap
import com.clientapi.pdm.infrastructure.PartConfig
import com.clientapi.pdm.infrastructure.RequestConfig
import com.clientapi.pdm.infrastructure.RequestMethod
import com.clientapi.pdm.infrastructure.ResponseType
import com.clientapi.pdm.infrastructure.Success
import com.clientapi.pdm.infrastructure.toMultiValue

open class NodesApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8443/api2/json")
        }
    }

    /**
     * POST /nodes/{node}/termproxy
     * Call termproxy and return shell ticket
     * Call termproxy and return shell ticket  Permissions: Restricted to users on realm &#39;pam&#39;
     * @param node Node name (or &#39;localhost&#39;)
     * @param nodesCreateTermproxyRequest  (optional)
     * @return NodesCreateTermproxyResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesCreateTermproxy(node: kotlin.String, nodesCreateTermproxyRequest: NodesCreateTermproxyRequest? = null) : NodesCreateTermproxyResponse {
        val localVarResponse = nodesCreateTermproxyWithHttpInfo(node = node, nodesCreateTermproxyRequest = nodesCreateTermproxyRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesCreateTermproxyResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /nodes/{node}/termproxy
     * Call termproxy and return shell ticket
     * Call termproxy and return shell ticket  Permissions: Restricted to users on realm &#39;pam&#39;
     * @param node Node name (or &#39;localhost&#39;)
     * @param nodesCreateTermproxyRequest  (optional)
     * @return ApiResponse<NodesCreateTermproxyResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesCreateTermproxyWithHttpInfo(node: kotlin.String, nodesCreateTermproxyRequest: NodesCreateTermproxyRequest?) : ApiResponse<NodesCreateTermproxyResponse?> {
        val localVariableConfig = nodesCreateTermproxyRequestConfig(node = node, nodesCreateTermproxyRequest = nodesCreateTermproxyRequest)

        return request<NodesCreateTermproxyRequest, NodesCreateTermproxyResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesCreateTermproxy
     *
     * @param node Node name (or &#39;localhost&#39;)
     * @param nodesCreateTermproxyRequest  (optional)
     * @return RequestConfig
     */
    fun nodesCreateTermproxyRequestConfig(node: kotlin.String, nodesCreateTermproxyRequest: NodesCreateTermproxyRequest?) : RequestConfig<NodesCreateTermproxyRequest> {
        val localVariableBody = nodesCreateTermproxyRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/nodes/{node}/termproxy".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /nodes/{node}/journal
     * Read syslog entries
     * Read syslog entries.
     * @param node Node name (or &#39;localhost&#39;)
     * @param endcursor End before the given Cursor. Conflicts with &#39;until&#39; (optional)
     * @param lastentries Limit to the last X lines. Conflicts with a range. (optional)
     * @param since Display all log since this UNIX epoch. Conflicts with &#39;startcursor&#39;. (optional)
     * @param startcursor Start after the given Cursor. Conflicts with &#39;since&#39;. (optional)
     * @param until Display all log until this UNIX epoch. Conflicts with &#39;endcursor&#39;. (optional)
     * @return NodesGetJournalResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesGetJournal(node: kotlin.String, endcursor: kotlin.String? = null, lastentries: kotlin.Long? = null, since: kotlin.Long? = null, startcursor: kotlin.String? = null, until: kotlin.Long? = null) : NodesGetJournalResponse {
        val localVarResponse = nodesGetJournalWithHttpInfo(node = node, endcursor = endcursor, lastentries = lastentries, since = since, startcursor = startcursor, until = until)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesGetJournalResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /nodes/{node}/journal
     * Read syslog entries
     * Read syslog entries.
     * @param node Node name (or &#39;localhost&#39;)
     * @param endcursor End before the given Cursor. Conflicts with &#39;until&#39; (optional)
     * @param lastentries Limit to the last X lines. Conflicts with a range. (optional)
     * @param since Display all log since this UNIX epoch. Conflicts with &#39;startcursor&#39;. (optional)
     * @param startcursor Start after the given Cursor. Conflicts with &#39;since&#39;. (optional)
     * @param until Display all log until this UNIX epoch. Conflicts with &#39;endcursor&#39;. (optional)
     * @return ApiResponse<NodesGetJournalResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesGetJournalWithHttpInfo(node: kotlin.String, endcursor: kotlin.String?, lastentries: kotlin.Long?, since: kotlin.Long?, startcursor: kotlin.String?, until: kotlin.Long?) : ApiResponse<NodesGetJournalResponse?> {
        val localVariableConfig = nodesGetJournalRequestConfig(node = node, endcursor = endcursor, lastentries = lastentries, since = since, startcursor = startcursor, until = until)

        return request<Unit, NodesGetJournalResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesGetJournal
     *
     * @param node Node name (or &#39;localhost&#39;)
     * @param endcursor End before the given Cursor. Conflicts with &#39;until&#39; (optional)
     * @param lastentries Limit to the last X lines. Conflicts with a range. (optional)
     * @param since Display all log since this UNIX epoch. Conflicts with &#39;startcursor&#39;. (optional)
     * @param startcursor Start after the given Cursor. Conflicts with &#39;since&#39;. (optional)
     * @param until Display all log until this UNIX epoch. Conflicts with &#39;endcursor&#39;. (optional)
     * @return RequestConfig
     */
    fun nodesGetJournalRequestConfig(node: kotlin.String, endcursor: kotlin.String?, lastentries: kotlin.Long?, since: kotlin.Long?, startcursor: kotlin.String?, until: kotlin.Long?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (endcursor != null) {
                    put("endcursor", listOf(endcursor.toString()))
                }
                if (lastentries != null) {
                    put("lastentries", listOf(lastentries.toString()))
                }
                if (since != null) {
                    put("since", listOf(since.toString()))
                }
                if (startcursor != null) {
                    put("startcursor", listOf(startcursor.toString()))
                }
                if (until != null) {
                    put("until", listOf(until.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/nodes/{node}/journal".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /nodes
     * List Nodes (only for compatibility)
     * List Nodes (only for compatibility)
     * @return NodesGetNodesResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesGetNodes() : NodesGetNodesResponse {
        val localVarResponse = nodesGetNodesWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesGetNodesResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /nodes
     * List Nodes (only for compatibility)
     * List Nodes (only for compatibility)
     * @return ApiResponse<NodesGetNodesResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesGetNodesWithHttpInfo() : ApiResponse<NodesGetNodesResponse?> {
        val localVariableConfig = nodesGetNodesRequestConfig()

        return request<Unit, NodesGetNodesResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesGetNodes
     *
     * @return RequestConfig
     */
    fun nodesGetNodesRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/nodes",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /nodes/{node}
     * Directory index
     * Directory index.
     * @param node 
     * @return NodesGetNodesByNodeResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesGetNodesByNode(node: kotlin.String) : NodesGetNodesByNodeResponse {
        val localVarResponse = nodesGetNodesByNodeWithHttpInfo(node = node)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesGetNodesByNodeResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /nodes/{node}
     * Directory index
     * Directory index.
     * @param node 
     * @return ApiResponse<NodesGetNodesByNodeResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesGetNodesByNodeWithHttpInfo(node: kotlin.String) : ApiResponse<NodesGetNodesByNodeResponse?> {
        val localVariableConfig = nodesGetNodesByNodeRequestConfig(node = node)

        return request<Unit, NodesGetNodesByNodeResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesGetNodesByNode
     *
     * @param node 
     * @return RequestConfig
     */
    fun nodesGetNodesByNodeRequestConfig(node: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/nodes/{node}".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /nodes/{node}/report
     * Get the system report for this node
     * Get the system report for this node.
     * @param node Node name (or &#39;localhost&#39;)
     * @return NodesGetReportResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesGetReport(node: kotlin.String) : NodesGetReportResponse {
        val localVarResponse = nodesGetReportWithHttpInfo(node = node)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesGetReportResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /nodes/{node}/report
     * Get the system report for this node
     * Get the system report for this node.
     * @param node Node name (or &#39;localhost&#39;)
     * @return ApiResponse<NodesGetReportResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesGetReportWithHttpInfo(node: kotlin.String) : ApiResponse<NodesGetReportResponse?> {
        val localVariableConfig = nodesGetReportRequestConfig(node = node)

        return request<Unit, NodesGetReportResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesGetReport
     *
     * @param node Node name (or &#39;localhost&#39;)
     * @return RequestConfig
     */
    fun nodesGetReportRequestConfig(node: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/nodes/{node}/report".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /nodes/{node}/rrdata
     * Read RRD data for this PDM node
     * Read RRD data for this PDM node.
     * @param node 
     * @param cf RRD consolidation mode
     * @param timeframe RRD time frame
     * @return NodesGetRrdataResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesGetRrdata(node: kotlin.String, cf: PdmCfEnum, timeframe: PdmTimeframeEnum) : NodesGetRrdataResponse {
        val localVarResponse = nodesGetRrdataWithHttpInfo(node = node, cf = cf, timeframe = timeframe)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesGetRrdataResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /nodes/{node}/rrdata
     * Read RRD data for this PDM node
     * Read RRD data for this PDM node.
     * @param node 
     * @param cf RRD consolidation mode
     * @param timeframe RRD time frame
     * @return ApiResponse<NodesGetRrdataResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesGetRrdataWithHttpInfo(node: kotlin.String, cf: PdmCfEnum, timeframe: PdmTimeframeEnum) : ApiResponse<NodesGetRrdataResponse?> {
        val localVariableConfig = nodesGetRrdataRequestConfig(node = node, cf = cf, timeframe = timeframe)

        return request<Unit, NodesGetRrdataResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesGetRrdata
     *
     * @param node 
     * @param cf RRD consolidation mode
     * @param timeframe RRD time frame
     * @return RequestConfig
     */
    fun nodesGetRrdataRequestConfig(node: kotlin.String, cf: PdmCfEnum, timeframe: PdmTimeframeEnum) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("cf", listOf(cf.toString()))
                put("timeframe", listOf(timeframe.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/nodes/{node}/rrdata".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /nodes/{node}/syslog
     * Read syslog entries
     * Read syslog entries.
     * @param node Node name (or &#39;localhost&#39;)
     * @param limit Max. number of lines. (optional)
     * @param service Service ID. (optional)
     * @param since Display all log since this date-time string. (optional)
     * @param start Start line number. (optional)
     * @param until Display all log until this date-time string. (optional)
     * @return NodesGetSyslogResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesGetSyslog(node: kotlin.String, limit: kotlin.Long? = null, service: kotlin.String? = null, since: kotlin.String? = null, start: kotlin.Long? = null, until: kotlin.String? = null) : NodesGetSyslogResponse {
        val localVarResponse = nodesGetSyslogWithHttpInfo(node = node, limit = limit, service = service, since = since, start = start, until = until)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesGetSyslogResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /nodes/{node}/syslog
     * Read syslog entries
     * Read syslog entries.
     * @param node Node name (or &#39;localhost&#39;)
     * @param limit Max. number of lines. (optional)
     * @param service Service ID. (optional)
     * @param since Display all log since this date-time string. (optional)
     * @param start Start line number. (optional)
     * @param until Display all log until this date-time string. (optional)
     * @return ApiResponse<NodesGetSyslogResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesGetSyslogWithHttpInfo(node: kotlin.String, limit: kotlin.Long?, service: kotlin.String?, since: kotlin.String?, start: kotlin.Long?, until: kotlin.String?) : ApiResponse<NodesGetSyslogResponse?> {
        val localVariableConfig = nodesGetSyslogRequestConfig(node = node, limit = limit, service = service, since = since, start = start, until = until)

        return request<Unit, NodesGetSyslogResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesGetSyslog
     *
     * @param node Node name (or &#39;localhost&#39;)
     * @param limit Max. number of lines. (optional)
     * @param service Service ID. (optional)
     * @param since Display all log since this date-time string. (optional)
     * @param start Start line number. (optional)
     * @param until Display all log until this date-time string. (optional)
     * @return RequestConfig
     */
    fun nodesGetSyslogRequestConfig(node: kotlin.String, limit: kotlin.Long?, service: kotlin.String?, since: kotlin.String?, start: kotlin.Long?, until: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (service != null) {
                    put("service", listOf(service.toString()))
                }
                if (since != null) {
                    put("since", listOf(since.toString()))
                }
                if (start != null) {
                    put("start", listOf(start.toString()))
                }
                if (until != null) {
                    put("until", listOf(until.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/nodes/{node}/syslog".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /nodes/{node}/vncwebsocket
     * Upgraded to websocket
     * Upgraded to websocket  Permissions: The user needs Sys.Console on /system.  Wire-level note: this endpoint answers HTTP 101 Upgrade, not a JSON body. The 200 schema below is the apidoc-declared shape for tooling, but real clients perform a WebSocket upgrade and exchange framed messages on the resulting socket. See the &#x60;x-pdm-websocket&#x60; extension for the framing and the list of sibling endpoints that issue tickets.
     * @param node Node name (or &#39;localhost&#39;)
     * @param port Terminal port
     * @param vncticket Terminal ticket
     * @return NodesGetVncwebsocketResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesGetVncwebsocket(node: kotlin.String, port: kotlin.Long, vncticket: kotlin.String) : NodesGetVncwebsocketResponse {
        val localVarResponse = nodesGetVncwebsocketWithHttpInfo(node = node, port = port, vncticket = vncticket)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesGetVncwebsocketResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /nodes/{node}/vncwebsocket
     * Upgraded to websocket
     * Upgraded to websocket  Permissions: The user needs Sys.Console on /system.  Wire-level note: this endpoint answers HTTP 101 Upgrade, not a JSON body. The 200 schema below is the apidoc-declared shape for tooling, but real clients perform a WebSocket upgrade and exchange framed messages on the resulting socket. See the &#x60;x-pdm-websocket&#x60; extension for the framing and the list of sibling endpoints that issue tickets.
     * @param node Node name (or &#39;localhost&#39;)
     * @param port Terminal port
     * @param vncticket Terminal ticket
     * @return ApiResponse<NodesGetVncwebsocketResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesGetVncwebsocketWithHttpInfo(node: kotlin.String, port: kotlin.Long, vncticket: kotlin.String) : ApiResponse<NodesGetVncwebsocketResponse?> {
        val localVariableConfig = nodesGetVncwebsocketRequestConfig(node = node, port = port, vncticket = vncticket)

        return request<Unit, NodesGetVncwebsocketResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesGetVncwebsocket
     *
     * @param node Node name (or &#39;localhost&#39;)
     * @param port Terminal port
     * @param vncticket Terminal ticket
     * @return RequestConfig
     */
    fun nodesGetVncwebsocketRequestConfig(node: kotlin.String, port: kotlin.Long, vncticket: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("port", listOf(port.toString()))
                put("vncticket", listOf(vncticket.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/nodes/{node}/vncwebsocket".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
