/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.clientapi.pdm.models.NodesConfigGetConfigResponse
import com.clientapi.pdm.models.NodesConfigUpdateConfigRequest
import com.clientapi.pdm.models.NodesConfigUpdateConfigResponse
import com.clientapi.pdm.models.PdmError

import com.squareup.moshi.Json

import com.clientapi.pdm.infrastructure.ApiClient
import com.clientapi.pdm.infrastructure.ApiResponse
import com.clientapi.pdm.infrastructure.ClientException
import com.clientapi.pdm.infrastructure.ClientError
import com.clientapi.pdm.infrastructure.ServerException
import com.clientapi.pdm.infrastructure.ServerError
import com.clientapi.pdm.infrastructure.MultiValueMap
import com.clientapi.pdm.infrastructure.PartConfig
import com.clientapi.pdm.infrastructure.RequestConfig
import com.clientapi.pdm.infrastructure.RequestMethod
import com.clientapi.pdm.infrastructure.ResponseType
import com.clientapi.pdm.infrastructure.Success
import com.clientapi.pdm.infrastructure.toMultiValue

open class NodesConfigApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8443/api2/json")
        }
    }

    /**
     * GET /nodes/{node}/config
     * Get the node configuration
     * Get the node configuration
     * @param node Node name (or &#39;localhost&#39;)
     * @return NodesConfigGetConfigResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesConfigGetConfig(node: kotlin.String) : NodesConfigGetConfigResponse {
        val localVarResponse = nodesConfigGetConfigWithHttpInfo(node = node)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesConfigGetConfigResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /nodes/{node}/config
     * Get the node configuration
     * Get the node configuration
     * @param node Node name (or &#39;localhost&#39;)
     * @return ApiResponse<NodesConfigGetConfigResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesConfigGetConfigWithHttpInfo(node: kotlin.String) : ApiResponse<NodesConfigGetConfigResponse?> {
        val localVariableConfig = nodesConfigGetConfigRequestConfig(node = node)

        return request<Unit, NodesConfigGetConfigResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesConfigGetConfig
     *
     * @param node Node name (or &#39;localhost&#39;)
     * @return RequestConfig
     */
    fun nodesConfigGetConfigRequestConfig(node: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/nodes/{node}/config".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /nodes/{node}/config
     * Update the node configuration
     * Update the node configuration
     * @param node Node name (or &#39;localhost&#39;)
     * @param nodesConfigUpdateConfigRequest  (optional)
     * @return NodesConfigUpdateConfigResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesConfigUpdateConfig(node: kotlin.String, nodesConfigUpdateConfigRequest: NodesConfigUpdateConfigRequest? = null) : NodesConfigUpdateConfigResponse {
        val localVarResponse = nodesConfigUpdateConfigWithHttpInfo(node = node, nodesConfigUpdateConfigRequest = nodesConfigUpdateConfigRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesConfigUpdateConfigResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /nodes/{node}/config
     * Update the node configuration
     * Update the node configuration
     * @param node Node name (or &#39;localhost&#39;)
     * @param nodesConfigUpdateConfigRequest  (optional)
     * @return ApiResponse<NodesConfigUpdateConfigResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesConfigUpdateConfigWithHttpInfo(node: kotlin.String, nodesConfigUpdateConfigRequest: NodesConfigUpdateConfigRequest?) : ApiResponse<NodesConfigUpdateConfigResponse?> {
        val localVariableConfig = nodesConfigUpdateConfigRequestConfig(node = node, nodesConfigUpdateConfigRequest = nodesConfigUpdateConfigRequest)

        return request<NodesConfigUpdateConfigRequest, NodesConfigUpdateConfigResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesConfigUpdateConfig
     *
     * @param node Node name (or &#39;localhost&#39;)
     * @param nodesConfigUpdateConfigRequest  (optional)
     * @return RequestConfig
     */
    fun nodesConfigUpdateConfigRequestConfig(node: kotlin.String, nodesConfigUpdateConfigRequest: NodesConfigUpdateConfigRequest?) : RequestConfig<NodesConfigUpdateConfigRequest> {
        val localVariableBody = nodesConfigUpdateConfigRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/nodes/{node}/config".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
