/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.clientapi.pdm.models.NodesNetworkCreateNetworkRequest
import com.clientapi.pdm.models.NodesNetworkCreateNetworkResponse
import com.clientapi.pdm.models.NodesNetworkDeleteNetworkResponse
import com.clientapi.pdm.models.NodesNetworkDeleteNodesByNodeNetworkByIfaceResponse
import com.clientapi.pdm.models.NodesNetworkGetNetworkResponse
import com.clientapi.pdm.models.NodesNetworkGetNodesByNodeNetworkByIfaceResponse
import com.clientapi.pdm.models.NodesNetworkUpdateNetworkResponse
import com.clientapi.pdm.models.NodesNetworkUpdateNodesByNodeNetworkByIfaceRequest
import com.clientapi.pdm.models.NodesNetworkUpdateNodesByNodeNetworkByIfaceResponse
import com.clientapi.pdm.models.PdmError

import com.squareup.moshi.Json

import com.clientapi.pdm.infrastructure.ApiClient
import com.clientapi.pdm.infrastructure.ApiResponse
import com.clientapi.pdm.infrastructure.ClientException
import com.clientapi.pdm.infrastructure.ClientError
import com.clientapi.pdm.infrastructure.ServerException
import com.clientapi.pdm.infrastructure.ServerError
import com.clientapi.pdm.infrastructure.MultiValueMap
import com.clientapi.pdm.infrastructure.PartConfig
import com.clientapi.pdm.infrastructure.RequestConfig
import com.clientapi.pdm.infrastructure.RequestMethod
import com.clientapi.pdm.infrastructure.ResponseType
import com.clientapi.pdm.infrastructure.Success
import com.clientapi.pdm.infrastructure.toMultiValue

open class NodesNetworkApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8443/api2/json")
        }
    }

    /**
     * POST /nodes/{node}/network
     * Create network interface configuration
     * Create network interface configuration.
     * @param node Node name (or &#39;localhost&#39;)
     * @param nodesNetworkCreateNetworkRequest 
     * @return NodesNetworkCreateNetworkResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesNetworkCreateNetwork(node: kotlin.String, nodesNetworkCreateNetworkRequest: NodesNetworkCreateNetworkRequest) : NodesNetworkCreateNetworkResponse {
        val localVarResponse = nodesNetworkCreateNetworkWithHttpInfo(node = node, nodesNetworkCreateNetworkRequest = nodesNetworkCreateNetworkRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesNetworkCreateNetworkResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /nodes/{node}/network
     * Create network interface configuration
     * Create network interface configuration.
     * @param node Node name (or &#39;localhost&#39;)
     * @param nodesNetworkCreateNetworkRequest 
     * @return ApiResponse<NodesNetworkCreateNetworkResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesNetworkCreateNetworkWithHttpInfo(node: kotlin.String, nodesNetworkCreateNetworkRequest: NodesNetworkCreateNetworkRequest) : ApiResponse<NodesNetworkCreateNetworkResponse?> {
        val localVariableConfig = nodesNetworkCreateNetworkRequestConfig(node = node, nodesNetworkCreateNetworkRequest = nodesNetworkCreateNetworkRequest)

        return request<NodesNetworkCreateNetworkRequest, NodesNetworkCreateNetworkResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesNetworkCreateNetwork
     *
     * @param node Node name (or &#39;localhost&#39;)
     * @param nodesNetworkCreateNetworkRequest 
     * @return RequestConfig
     */
    fun nodesNetworkCreateNetworkRequestConfig(node: kotlin.String, nodesNetworkCreateNetworkRequest: NodesNetworkCreateNetworkRequest) : RequestConfig<NodesNetworkCreateNetworkRequest> {
        val localVariableBody = nodesNetworkCreateNetworkRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/nodes/{node}/network".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /nodes/{node}/network
     * Revert network configuration (rm /etc/network/interfaces
     * Revert network configuration (rm /etc/network/interfaces.new).
     * @param node Node name (or &#39;localhost&#39;)
     * @return NodesNetworkDeleteNetworkResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesNetworkDeleteNetwork(node: kotlin.String) : NodesNetworkDeleteNetworkResponse {
        val localVarResponse = nodesNetworkDeleteNetworkWithHttpInfo(node = node)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesNetworkDeleteNetworkResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /nodes/{node}/network
     * Revert network configuration (rm /etc/network/interfaces
     * Revert network configuration (rm /etc/network/interfaces.new).
     * @param node Node name (or &#39;localhost&#39;)
     * @return ApiResponse<NodesNetworkDeleteNetworkResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesNetworkDeleteNetworkWithHttpInfo(node: kotlin.String) : ApiResponse<NodesNetworkDeleteNetworkResponse?> {
        val localVariableConfig = nodesNetworkDeleteNetworkRequestConfig(node = node)

        return request<Unit, NodesNetworkDeleteNetworkResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesNetworkDeleteNetwork
     *
     * @param node Node name (or &#39;localhost&#39;)
     * @return RequestConfig
     */
    fun nodesNetworkDeleteNetworkRequestConfig(node: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/nodes/{node}/network".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /nodes/{node}/network/{iface}
     * Remove network interface configuration
     * Remove network interface configuration.
     * @param iface Network interface name.
     * @param node Node name (or &#39;localhost&#39;)
     * @param digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications. (optional)
     * @return NodesNetworkDeleteNodesByNodeNetworkByIfaceResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesNetworkDeleteNodesByNodeNetworkByIface(iface: kotlin.String, node: kotlin.String, digest: kotlin.String? = null) : NodesNetworkDeleteNodesByNodeNetworkByIfaceResponse {
        val localVarResponse = nodesNetworkDeleteNodesByNodeNetworkByIfaceWithHttpInfo(iface = iface, node = node, digest = digest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesNetworkDeleteNodesByNodeNetworkByIfaceResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /nodes/{node}/network/{iface}
     * Remove network interface configuration
     * Remove network interface configuration.
     * @param iface Network interface name.
     * @param node Node name (or &#39;localhost&#39;)
     * @param digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications. (optional)
     * @return ApiResponse<NodesNetworkDeleteNodesByNodeNetworkByIfaceResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesNetworkDeleteNodesByNodeNetworkByIfaceWithHttpInfo(iface: kotlin.String, node: kotlin.String, digest: kotlin.String?) : ApiResponse<NodesNetworkDeleteNodesByNodeNetworkByIfaceResponse?> {
        val localVariableConfig = nodesNetworkDeleteNodesByNodeNetworkByIfaceRequestConfig(iface = iface, node = node, digest = digest)

        return request<Unit, NodesNetworkDeleteNodesByNodeNetworkByIfaceResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesNetworkDeleteNodesByNodeNetworkByIface
     *
     * @param iface Network interface name.
     * @param node Node name (or &#39;localhost&#39;)
     * @param digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications. (optional)
     * @return RequestConfig
     */
    fun nodesNetworkDeleteNodesByNodeNetworkByIfaceRequestConfig(iface: kotlin.String, node: kotlin.String, digest: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (digest != null) {
                    put("digest", listOf(digest.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/nodes/{node}/network/{iface}".replace("{"+"iface"+"}", encodeURIComponent(iface.toString())).replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /nodes/{node}/network
     * List all network devices
     * List all network devices
     * @param node Node name (or &#39;localhost&#39;)
     * @return NodesNetworkGetNetworkResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesNetworkGetNetwork(node: kotlin.String) : NodesNetworkGetNetworkResponse {
        val localVarResponse = nodesNetworkGetNetworkWithHttpInfo(node = node)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesNetworkGetNetworkResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /nodes/{node}/network
     * List all network devices
     * List all network devices
     * @param node Node name (or &#39;localhost&#39;)
     * @return ApiResponse<NodesNetworkGetNetworkResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesNetworkGetNetworkWithHttpInfo(node: kotlin.String) : ApiResponse<NodesNetworkGetNetworkResponse?> {
        val localVariableConfig = nodesNetworkGetNetworkRequestConfig(node = node)

        return request<Unit, NodesNetworkGetNetworkResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesNetworkGetNetwork
     *
     * @param node Node name (or &#39;localhost&#39;)
     * @return RequestConfig
     */
    fun nodesNetworkGetNetworkRequestConfig(node: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/nodes/{node}/network".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /nodes/{node}/network/{iface}
     * Read a network interface configuration
     * Read a network interface configuration.
     * @param iface Network interface name.
     * @param node Node name (or &#39;localhost&#39;)
     * @return NodesNetworkGetNodesByNodeNetworkByIfaceResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesNetworkGetNodesByNodeNetworkByIface(iface: kotlin.String, node: kotlin.String) : NodesNetworkGetNodesByNodeNetworkByIfaceResponse {
        val localVarResponse = nodesNetworkGetNodesByNodeNetworkByIfaceWithHttpInfo(iface = iface, node = node)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesNetworkGetNodesByNodeNetworkByIfaceResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /nodes/{node}/network/{iface}
     * Read a network interface configuration
     * Read a network interface configuration.
     * @param iface Network interface name.
     * @param node Node name (or &#39;localhost&#39;)
     * @return ApiResponse<NodesNetworkGetNodesByNodeNetworkByIfaceResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesNetworkGetNodesByNodeNetworkByIfaceWithHttpInfo(iface: kotlin.String, node: kotlin.String) : ApiResponse<NodesNetworkGetNodesByNodeNetworkByIfaceResponse?> {
        val localVariableConfig = nodesNetworkGetNodesByNodeNetworkByIfaceRequestConfig(iface = iface, node = node)

        return request<Unit, NodesNetworkGetNodesByNodeNetworkByIfaceResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesNetworkGetNodesByNodeNetworkByIface
     *
     * @param iface Network interface name.
     * @param node Node name (or &#39;localhost&#39;)
     * @return RequestConfig
     */
    fun nodesNetworkGetNodesByNodeNetworkByIfaceRequestConfig(iface: kotlin.String, node: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/nodes/{node}/network/{iface}".replace("{"+"iface"+"}", encodeURIComponent(iface.toString())).replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /nodes/{node}/network
     * Reload network configuration (requires ifupdown2)
     * Reload network configuration (requires ifupdown2).
     * @param node Node name (or &#39;localhost&#39;)
     * @return NodesNetworkUpdateNetworkResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesNetworkUpdateNetwork(node: kotlin.String) : NodesNetworkUpdateNetworkResponse {
        val localVarResponse = nodesNetworkUpdateNetworkWithHttpInfo(node = node)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesNetworkUpdateNetworkResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /nodes/{node}/network
     * Reload network configuration (requires ifupdown2)
     * Reload network configuration (requires ifupdown2).
     * @param node Node name (or &#39;localhost&#39;)
     * @return ApiResponse<NodesNetworkUpdateNetworkResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesNetworkUpdateNetworkWithHttpInfo(node: kotlin.String) : ApiResponse<NodesNetworkUpdateNetworkResponse?> {
        val localVariableConfig = nodesNetworkUpdateNetworkRequestConfig(node = node)

        return request<Unit, NodesNetworkUpdateNetworkResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesNetworkUpdateNetwork
     *
     * @param node Node name (or &#39;localhost&#39;)
     * @return RequestConfig
     */
    fun nodesNetworkUpdateNetworkRequestConfig(node: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/nodes/{node}/network".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /nodes/{node}/network/{iface}
     * Update network interface config
     * Update network interface config.
     * @param iface Network interface name.
     * @param node Node name (or &#39;localhost&#39;)
     * @param nodesNetworkUpdateNodesByNodeNetworkByIfaceRequest  (optional)
     * @return NodesNetworkUpdateNodesByNodeNetworkByIfaceResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesNetworkUpdateNodesByNodeNetworkByIface(iface: kotlin.String, node: kotlin.String, nodesNetworkUpdateNodesByNodeNetworkByIfaceRequest: NodesNetworkUpdateNodesByNodeNetworkByIfaceRequest? = null) : NodesNetworkUpdateNodesByNodeNetworkByIfaceResponse {
        val localVarResponse = nodesNetworkUpdateNodesByNodeNetworkByIfaceWithHttpInfo(iface = iface, node = node, nodesNetworkUpdateNodesByNodeNetworkByIfaceRequest = nodesNetworkUpdateNodesByNodeNetworkByIfaceRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesNetworkUpdateNodesByNodeNetworkByIfaceResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /nodes/{node}/network/{iface}
     * Update network interface config
     * Update network interface config.
     * @param iface Network interface name.
     * @param node Node name (or &#39;localhost&#39;)
     * @param nodesNetworkUpdateNodesByNodeNetworkByIfaceRequest  (optional)
     * @return ApiResponse<NodesNetworkUpdateNodesByNodeNetworkByIfaceResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesNetworkUpdateNodesByNodeNetworkByIfaceWithHttpInfo(iface: kotlin.String, node: kotlin.String, nodesNetworkUpdateNodesByNodeNetworkByIfaceRequest: NodesNetworkUpdateNodesByNodeNetworkByIfaceRequest?) : ApiResponse<NodesNetworkUpdateNodesByNodeNetworkByIfaceResponse?> {
        val localVariableConfig = nodesNetworkUpdateNodesByNodeNetworkByIfaceRequestConfig(iface = iface, node = node, nodesNetworkUpdateNodesByNodeNetworkByIfaceRequest = nodesNetworkUpdateNodesByNodeNetworkByIfaceRequest)

        return request<NodesNetworkUpdateNodesByNodeNetworkByIfaceRequest, NodesNetworkUpdateNodesByNodeNetworkByIfaceResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesNetworkUpdateNodesByNodeNetworkByIface
     *
     * @param iface Network interface name.
     * @param node Node name (or &#39;localhost&#39;)
     * @param nodesNetworkUpdateNodesByNodeNetworkByIfaceRequest  (optional)
     * @return RequestConfig
     */
    fun nodesNetworkUpdateNodesByNodeNetworkByIfaceRequestConfig(iface: kotlin.String, node: kotlin.String, nodesNetworkUpdateNodesByNodeNetworkByIfaceRequest: NodesNetworkUpdateNodesByNodeNetworkByIfaceRequest?) : RequestConfig<NodesNetworkUpdateNodesByNodeNetworkByIfaceRequest> {
        val localVariableBody = nodesNetworkUpdateNodesByNodeNetworkByIfaceRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/nodes/{node}/network/{iface}".replace("{"+"iface"+"}", encodeURIComponent(iface.toString())).replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
