/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.clientapi.pdm.models.NodesDnsGetDnsResponse
import com.clientapi.pdm.models.NodesDnsUpdateDnsRequest
import com.clientapi.pdm.models.NodesDnsUpdateDnsResponse
import com.clientapi.pdm.models.PdmError

import com.squareup.moshi.Json

import com.clientapi.pdm.infrastructure.ApiClient
import com.clientapi.pdm.infrastructure.ApiResponse
import com.clientapi.pdm.infrastructure.ClientException
import com.clientapi.pdm.infrastructure.ClientError
import com.clientapi.pdm.infrastructure.ServerException
import com.clientapi.pdm.infrastructure.ServerError
import com.clientapi.pdm.infrastructure.MultiValueMap
import com.clientapi.pdm.infrastructure.PartConfig
import com.clientapi.pdm.infrastructure.RequestConfig
import com.clientapi.pdm.infrastructure.RequestMethod
import com.clientapi.pdm.infrastructure.ResponseType
import com.clientapi.pdm.infrastructure.Success
import com.clientapi.pdm.infrastructure.toMultiValue

open class NodesDnsApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8443/api2/json")
        }
    }

    /**
     * GET /nodes/{node}/dns
     * Read DNS settings
     * Read DNS settings.
     * @param node Node name (or &#39;localhost&#39;)
     * @return NodesDnsGetDnsResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesDnsGetDns(node: kotlin.String) : NodesDnsGetDnsResponse {
        val localVarResponse = nodesDnsGetDnsWithHttpInfo(node = node)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesDnsGetDnsResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /nodes/{node}/dns
     * Read DNS settings
     * Read DNS settings.
     * @param node Node name (or &#39;localhost&#39;)
     * @return ApiResponse<NodesDnsGetDnsResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesDnsGetDnsWithHttpInfo(node: kotlin.String) : ApiResponse<NodesDnsGetDnsResponse?> {
        val localVariableConfig = nodesDnsGetDnsRequestConfig(node = node)

        return request<Unit, NodesDnsGetDnsResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesDnsGetDns
     *
     * @param node Node name (or &#39;localhost&#39;)
     * @return RequestConfig
     */
    fun nodesDnsGetDnsRequestConfig(node: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/nodes/{node}/dns".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /nodes/{node}/dns
     * Update DNS settings
     * Update DNS settings.
     * @param node Node name (or &#39;localhost&#39;)
     * @param nodesDnsUpdateDnsRequest  (optional)
     * @return NodesDnsUpdateDnsResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesDnsUpdateDns(node: kotlin.String, nodesDnsUpdateDnsRequest: NodesDnsUpdateDnsRequest? = null) : NodesDnsUpdateDnsResponse {
        val localVarResponse = nodesDnsUpdateDnsWithHttpInfo(node = node, nodesDnsUpdateDnsRequest = nodesDnsUpdateDnsRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesDnsUpdateDnsResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /nodes/{node}/dns
     * Update DNS settings
     * Update DNS settings.
     * @param node Node name (or &#39;localhost&#39;)
     * @param nodesDnsUpdateDnsRequest  (optional)
     * @return ApiResponse<NodesDnsUpdateDnsResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesDnsUpdateDnsWithHttpInfo(node: kotlin.String, nodesDnsUpdateDnsRequest: NodesDnsUpdateDnsRequest?) : ApiResponse<NodesDnsUpdateDnsResponse?> {
        val localVariableConfig = nodesDnsUpdateDnsRequestConfig(node = node, nodesDnsUpdateDnsRequest = nodesDnsUpdateDnsRequest)

        return request<NodesDnsUpdateDnsRequest, NodesDnsUpdateDnsResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesDnsUpdateDns
     *
     * @param node Node name (or &#39;localhost&#39;)
     * @param nodesDnsUpdateDnsRequest  (optional)
     * @return RequestConfig
     */
    fun nodesDnsUpdateDnsRequestConfig(node: kotlin.String, nodesDnsUpdateDnsRequest: NodesDnsUpdateDnsRequest?) : RequestConfig<NodesDnsUpdateDnsRequest> {
        val localVariableBody = nodesDnsUpdateDnsRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/nodes/{node}/dns".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
