/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.clientapi.pdm.models.PbsCreateProbeTlsRequest
import com.clientapi.pdm.models.PbsCreateProbeTlsResponse
import com.clientapi.pdm.models.PbsCreateScanRequest
import com.clientapi.pdm.models.PbsCreateScanResponse
import com.clientapi.pdm.models.PbsGetPbsResponse
import com.clientapi.pdm.models.PdmError

import com.squareup.moshi.Json

import com.clientapi.pdm.infrastructure.ApiClient
import com.clientapi.pdm.infrastructure.ApiResponse
import com.clientapi.pdm.infrastructure.ClientException
import com.clientapi.pdm.infrastructure.ClientError
import com.clientapi.pdm.infrastructure.ServerException
import com.clientapi.pdm.infrastructure.ServerError
import com.clientapi.pdm.infrastructure.MultiValueMap
import com.clientapi.pdm.infrastructure.PartConfig
import com.clientapi.pdm.infrastructure.RequestConfig
import com.clientapi.pdm.infrastructure.RequestMethod
import com.clientapi.pdm.infrastructure.ResponseType
import com.clientapi.pdm.infrastructure.Success
import com.clientapi.pdm.infrastructure.toMultiValue

open class PbsApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8443/api2/json")
        }
    }

    /**
     * POST /pbs/probe-tls
     * Probe the hosts TLS certificate
     * Probe the hosts TLS certificate.  If the certificate is not trusted with the given parameters, returns the certificate information.
     * @param pbsCreateProbeTlsRequest 
     * @return PbsCreateProbeTlsResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun pbsCreateProbeTls(pbsCreateProbeTlsRequest: PbsCreateProbeTlsRequest) : PbsCreateProbeTlsResponse {
        val localVarResponse = pbsCreateProbeTlsWithHttpInfo(pbsCreateProbeTlsRequest = pbsCreateProbeTlsRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as PbsCreateProbeTlsResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /pbs/probe-tls
     * Probe the hosts TLS certificate
     * Probe the hosts TLS certificate.  If the certificate is not trusted with the given parameters, returns the certificate information.
     * @param pbsCreateProbeTlsRequest 
     * @return ApiResponse<PbsCreateProbeTlsResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun pbsCreateProbeTlsWithHttpInfo(pbsCreateProbeTlsRequest: PbsCreateProbeTlsRequest) : ApiResponse<PbsCreateProbeTlsResponse?> {
        val localVariableConfig = pbsCreateProbeTlsRequestConfig(pbsCreateProbeTlsRequest = pbsCreateProbeTlsRequest)

        return request<PbsCreateProbeTlsRequest, PbsCreateProbeTlsResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation pbsCreateProbeTls
     *
     * @param pbsCreateProbeTlsRequest 
     * @return RequestConfig
     */
    fun pbsCreateProbeTlsRequestConfig(pbsCreateProbeTlsRequest: PbsCreateProbeTlsRequest) : RequestConfig<PbsCreateProbeTlsRequest> {
        val localVariableBody = pbsCreateProbeTlsRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/pbs/probe-tls",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /pbs/scan
     * Scans the given connection info for pbs host information
     * Scans the given connection info for pbs host information.  Checks login using the provided credentials.
     * @param pbsCreateScanRequest 
     * @return PbsCreateScanResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun pbsCreateScan(pbsCreateScanRequest: PbsCreateScanRequest) : PbsCreateScanResponse {
        val localVarResponse = pbsCreateScanWithHttpInfo(pbsCreateScanRequest = pbsCreateScanRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as PbsCreateScanResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /pbs/scan
     * Scans the given connection info for pbs host information
     * Scans the given connection info for pbs host information.  Checks login using the provided credentials.
     * @param pbsCreateScanRequest 
     * @return ApiResponse<PbsCreateScanResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun pbsCreateScanWithHttpInfo(pbsCreateScanRequest: PbsCreateScanRequest) : ApiResponse<PbsCreateScanResponse?> {
        val localVariableConfig = pbsCreateScanRequestConfig(pbsCreateScanRequest = pbsCreateScanRequest)

        return request<PbsCreateScanRequest, PbsCreateScanResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation pbsCreateScan
     *
     * @param pbsCreateScanRequest 
     * @return RequestConfig
     */
    fun pbsCreateScanRequestConfig(pbsCreateScanRequest: PbsCreateScanRequest) : RequestConfig<PbsCreateScanRequest> {
        val localVariableBody = pbsCreateScanRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/pbs/scan",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /pbs
     * Directory index
     * Directory index.
     * @return PbsGetPbsResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun pbsGetPbs() : PbsGetPbsResponse {
        val localVarResponse = pbsGetPbsWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as PbsGetPbsResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /pbs
     * Directory index
     * Directory index.
     * @return ApiResponse<PbsGetPbsResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun pbsGetPbsWithHttpInfo() : ApiResponse<PbsGetPbsResponse?> {
        val localVariableConfig = pbsGetPbsRequestConfig()

        return request<Unit, PbsGetPbsResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation pbsGetPbs
     *
     * @return RequestConfig
     */
    fun pbsGetPbsRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/pbs",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
