/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.clientapi.pdm.models.PdmError
import com.clientapi.pdm.models.PingGetPingResponse

import com.squareup.moshi.Json

import com.clientapi.pdm.infrastructure.ApiClient
import com.clientapi.pdm.infrastructure.ApiResponse
import com.clientapi.pdm.infrastructure.ClientException
import com.clientapi.pdm.infrastructure.ClientError
import com.clientapi.pdm.infrastructure.ServerException
import com.clientapi.pdm.infrastructure.ServerError
import com.clientapi.pdm.infrastructure.MultiValueMap
import com.clientapi.pdm.infrastructure.PartConfig
import com.clientapi.pdm.infrastructure.RequestConfig
import com.clientapi.pdm.infrastructure.RequestMethod
import com.clientapi.pdm.infrastructure.ResponseType
import com.clientapi.pdm.infrastructure.Success
import com.clientapi.pdm.infrastructure.toMultiValue

open class PingApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8443/api2/json")
        }
    }

    /**
     * GET /ping
     * A simple ping method
     * A simple ping method. returns \&quot;pong\&quot;  Permissions: Anyone can access this, just a cheap check if the API daemon is online.
     * @return PingGetPingResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun pingGetPing() : PingGetPingResponse {
        val localVarResponse = pingGetPingWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as PingGetPingResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /ping
     * A simple ping method
     * A simple ping method. returns \&quot;pong\&quot;  Permissions: Anyone can access this, just a cheap check if the API daemon is online.
     * @return ApiResponse<PingGetPingResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun pingGetPingWithHttpInfo() : ApiResponse<PingGetPingResponse?> {
        val localVariableConfig = pingGetPingRequestConfig()

        return request<Unit, PingGetPingResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation pingGetPing
     *
     * @return RequestConfig
     */
    fun pingGetPingRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/ping",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
