/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.clientapi.pdm.models.PdmError
import com.clientapi.pdm.models.PdmStatusfilterEnum
import com.clientapi.pdm.models.RemotesTasksGetListResponse
import com.clientapi.pdm.models.RemotesTasksGetStatisticsResponse
import com.clientapi.pdm.models.RemotesTasksGetTasksResponse

import com.squareup.moshi.Json

import com.clientapi.pdm.infrastructure.ApiClient
import com.clientapi.pdm.infrastructure.ApiResponse
import com.clientapi.pdm.infrastructure.ClientException
import com.clientapi.pdm.infrastructure.ClientError
import com.clientapi.pdm.infrastructure.ServerException
import com.clientapi.pdm.infrastructure.ServerError
import com.clientapi.pdm.infrastructure.MultiValueMap
import com.clientapi.pdm.infrastructure.PartConfig
import com.clientapi.pdm.infrastructure.RequestConfig
import com.clientapi.pdm.infrastructure.RequestMethod
import com.clientapi.pdm.infrastructure.ResponseType
import com.clientapi.pdm.infrastructure.Success
import com.clientapi.pdm.infrastructure.toMultiValue

open class RemotesTasksApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8443/api2/json")
        }
    }

    /**
     * GET /remotes/tasks/list
     * Get the list of tasks for all remotes
     * Get the list of tasks for all remotes.  Permissions: Resource.Audit privileges on /resource/{remote} are needed to list tasks from a given remote.
     * @param errors Only list erroneous tasks. (optional, default to 0)
     * @param limit Only list this amount of tasks. (0 means no limit) (optional, default to 50L)
     * @param remote Remote ID. (optional)
     * @param running Only list running tasks. (optional, default to 0)
     * @param since Only list tasks since this UNIX epoch. (optional)
     * @param start List tasks beginning from this offset. (optional, default to 0L)
     * @param statusfilter Only list tasks which have any one of the listed status. (optional)
     * @param typefilter Only list tasks whose type contains this. (optional)
     * @param until Only list tasks until this UNIX epoch. (optional)
     * @param userfilter Only list tasks from this user. (optional)
     * @param view View name. (optional)
     * @return RemotesTasksGetListResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun remotesTasksGetList(errors: kotlin.Boolean? = 0, limit: kotlin.Long? = 50L, remote: kotlin.String? = null, running: kotlin.Boolean? = 0, since: kotlin.Long? = null, start: kotlin.Long? = 0L, statusfilter: kotlin.collections.List<PdmStatusfilterEnum>? = null, typefilter: kotlin.String? = null, until: kotlin.Long? = null, userfilter: kotlin.String? = null, view: kotlin.String? = null) : RemotesTasksGetListResponse {
        val localVarResponse = remotesTasksGetListWithHttpInfo(errors = errors, limit = limit, remote = remote, running = running, since = since, start = start, statusfilter = statusfilter, typefilter = typefilter, until = until, userfilter = userfilter, view = view)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as RemotesTasksGetListResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /remotes/tasks/list
     * Get the list of tasks for all remotes
     * Get the list of tasks for all remotes.  Permissions: Resource.Audit privileges on /resource/{remote} are needed to list tasks from a given remote.
     * @param errors Only list erroneous tasks. (optional, default to 0)
     * @param limit Only list this amount of tasks. (0 means no limit) (optional, default to 50L)
     * @param remote Remote ID. (optional)
     * @param running Only list running tasks. (optional, default to 0)
     * @param since Only list tasks since this UNIX epoch. (optional)
     * @param start List tasks beginning from this offset. (optional, default to 0L)
     * @param statusfilter Only list tasks which have any one of the listed status. (optional)
     * @param typefilter Only list tasks whose type contains this. (optional)
     * @param until Only list tasks until this UNIX epoch. (optional)
     * @param userfilter Only list tasks from this user. (optional)
     * @param view View name. (optional)
     * @return ApiResponse<RemotesTasksGetListResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun remotesTasksGetListWithHttpInfo(errors: kotlin.Boolean?, limit: kotlin.Long?, remote: kotlin.String?, running: kotlin.Boolean?, since: kotlin.Long?, start: kotlin.Long?, statusfilter: kotlin.collections.List<PdmStatusfilterEnum>?, typefilter: kotlin.String?, until: kotlin.Long?, userfilter: kotlin.String?, view: kotlin.String?) : ApiResponse<RemotesTasksGetListResponse?> {
        val localVariableConfig = remotesTasksGetListRequestConfig(errors = errors, limit = limit, remote = remote, running = running, since = since, start = start, statusfilter = statusfilter, typefilter = typefilter, until = until, userfilter = userfilter, view = view)

        return request<Unit, RemotesTasksGetListResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation remotesTasksGetList
     *
     * @param errors Only list erroneous tasks. (optional, default to 0)
     * @param limit Only list this amount of tasks. (0 means no limit) (optional, default to 50L)
     * @param remote Remote ID. (optional)
     * @param running Only list running tasks. (optional, default to 0)
     * @param since Only list tasks since this UNIX epoch. (optional)
     * @param start List tasks beginning from this offset. (optional, default to 0L)
     * @param statusfilter Only list tasks which have any one of the listed status. (optional)
     * @param typefilter Only list tasks whose type contains this. (optional)
     * @param until Only list tasks until this UNIX epoch. (optional)
     * @param userfilter Only list tasks from this user. (optional)
     * @param view View name. (optional)
     * @return RequestConfig
     */
    fun remotesTasksGetListRequestConfig(errors: kotlin.Boolean?, limit: kotlin.Long?, remote: kotlin.String?, running: kotlin.Boolean?, since: kotlin.Long?, start: kotlin.Long?, statusfilter: kotlin.collections.List<PdmStatusfilterEnum>?, typefilter: kotlin.String?, until: kotlin.Long?, userfilter: kotlin.String?, view: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (errors != null) {
                    put("errors", listOf(errors.toString()))
                }
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (remote != null) {
                    put("remote", listOf(remote.toString()))
                }
                if (running != null) {
                    put("running", listOf(running.toString()))
                }
                if (since != null) {
                    put("since", listOf(since.toString()))
                }
                if (start != null) {
                    put("start", listOf(start.toString()))
                }
                if (statusfilter != null) {
                    put("statusfilter", toMultiValue(statusfilter.toList(), "multi"))
                }
                if (typefilter != null) {
                    put("typefilter", listOf(typefilter.toString()))
                }
                if (until != null) {
                    put("until", listOf(until.toString()))
                }
                if (userfilter != null) {
                    put("userfilter", listOf(userfilter.toString()))
                }
                if (view != null) {
                    put("view", listOf(view.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/remotes/tasks/list",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /remotes/tasks/statistics
     * Get task statistics for the specified filters
     * Get task statistics for the specified filters.  Permissions: Resource.Audit privileges on /resource/{remote} are needed to list tasks from a given remote.
     * @param errors Only list erroneous tasks. (optional, default to 0)
     * @param limit Only list this amount of tasks. (0 means no limit) (optional, default to 50L)
     * @param remote Remote ID. (optional)
     * @param running Only list running tasks. (optional, default to 0)
     * @param since Only list tasks since this UNIX epoch. (optional)
     * @param start List tasks beginning from this offset. (optional, default to 0L)
     * @param statusfilter Only list tasks which have any one of the listed status. (optional)
     * @param typefilter Only list tasks whose type contains this. (optional)
     * @param until Only list tasks until this UNIX epoch. (optional)
     * @param userfilter Only list tasks from this user. (optional)
     * @param view View name. (optional)
     * @return RemotesTasksGetStatisticsResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun remotesTasksGetStatistics(errors: kotlin.Boolean? = 0, limit: kotlin.Long? = 50L, remote: kotlin.String? = null, running: kotlin.Boolean? = 0, since: kotlin.Long? = null, start: kotlin.Long? = 0L, statusfilter: kotlin.collections.List<PdmStatusfilterEnum>? = null, typefilter: kotlin.String? = null, until: kotlin.Long? = null, userfilter: kotlin.String? = null, view: kotlin.String? = null) : RemotesTasksGetStatisticsResponse {
        val localVarResponse = remotesTasksGetStatisticsWithHttpInfo(errors = errors, limit = limit, remote = remote, running = running, since = since, start = start, statusfilter = statusfilter, typefilter = typefilter, until = until, userfilter = userfilter, view = view)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as RemotesTasksGetStatisticsResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /remotes/tasks/statistics
     * Get task statistics for the specified filters
     * Get task statistics for the specified filters.  Permissions: Resource.Audit privileges on /resource/{remote} are needed to list tasks from a given remote.
     * @param errors Only list erroneous tasks. (optional, default to 0)
     * @param limit Only list this amount of tasks. (0 means no limit) (optional, default to 50L)
     * @param remote Remote ID. (optional)
     * @param running Only list running tasks. (optional, default to 0)
     * @param since Only list tasks since this UNIX epoch. (optional)
     * @param start List tasks beginning from this offset. (optional, default to 0L)
     * @param statusfilter Only list tasks which have any one of the listed status. (optional)
     * @param typefilter Only list tasks whose type contains this. (optional)
     * @param until Only list tasks until this UNIX epoch. (optional)
     * @param userfilter Only list tasks from this user. (optional)
     * @param view View name. (optional)
     * @return ApiResponse<RemotesTasksGetStatisticsResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun remotesTasksGetStatisticsWithHttpInfo(errors: kotlin.Boolean?, limit: kotlin.Long?, remote: kotlin.String?, running: kotlin.Boolean?, since: kotlin.Long?, start: kotlin.Long?, statusfilter: kotlin.collections.List<PdmStatusfilterEnum>?, typefilter: kotlin.String?, until: kotlin.Long?, userfilter: kotlin.String?, view: kotlin.String?) : ApiResponse<RemotesTasksGetStatisticsResponse?> {
        val localVariableConfig = remotesTasksGetStatisticsRequestConfig(errors = errors, limit = limit, remote = remote, running = running, since = since, start = start, statusfilter = statusfilter, typefilter = typefilter, until = until, userfilter = userfilter, view = view)

        return request<Unit, RemotesTasksGetStatisticsResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation remotesTasksGetStatistics
     *
     * @param errors Only list erroneous tasks. (optional, default to 0)
     * @param limit Only list this amount of tasks. (0 means no limit) (optional, default to 50L)
     * @param remote Remote ID. (optional)
     * @param running Only list running tasks. (optional, default to 0)
     * @param since Only list tasks since this UNIX epoch. (optional)
     * @param start List tasks beginning from this offset. (optional, default to 0L)
     * @param statusfilter Only list tasks which have any one of the listed status. (optional)
     * @param typefilter Only list tasks whose type contains this. (optional)
     * @param until Only list tasks until this UNIX epoch. (optional)
     * @param userfilter Only list tasks from this user. (optional)
     * @param view View name. (optional)
     * @return RequestConfig
     */
    fun remotesTasksGetStatisticsRequestConfig(errors: kotlin.Boolean?, limit: kotlin.Long?, remote: kotlin.String?, running: kotlin.Boolean?, since: kotlin.Long?, start: kotlin.Long?, statusfilter: kotlin.collections.List<PdmStatusfilterEnum>?, typefilter: kotlin.String?, until: kotlin.Long?, userfilter: kotlin.String?, view: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (errors != null) {
                    put("errors", listOf(errors.toString()))
                }
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (remote != null) {
                    put("remote", listOf(remote.toString()))
                }
                if (running != null) {
                    put("running", listOf(running.toString()))
                }
                if (since != null) {
                    put("since", listOf(since.toString()))
                }
                if (start != null) {
                    put("start", listOf(start.toString()))
                }
                if (statusfilter != null) {
                    put("statusfilter", toMultiValue(statusfilter.toList(), "multi"))
                }
                if (typefilter != null) {
                    put("typefilter", listOf(typefilter.toString()))
                }
                if (until != null) {
                    put("until", listOf(until.toString()))
                }
                if (userfilter != null) {
                    put("userfilter", listOf(userfilter.toString()))
                }
                if (view != null) {
                    put("view", listOf(view.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/remotes/tasks/statistics",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /remotes/tasks
     * Directory index
     * Directory index.
     * @return RemotesTasksGetTasksResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun remotesTasksGetTasks() : RemotesTasksGetTasksResponse {
        val localVarResponse = remotesTasksGetTasksWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as RemotesTasksGetTasksResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /remotes/tasks
     * Directory index
     * Directory index.
     * @return ApiResponse<RemotesTasksGetTasksResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun remotesTasksGetTasksWithHttpInfo() : ApiResponse<RemotesTasksGetTasksResponse?> {
        val localVariableConfig = remotesTasksGetTasksRequestConfig()

        return request<Unit, RemotesTasksGetTasksResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation remotesTasksGetTasks
     *
     * @return RequestConfig
     */
    fun remotesTasksGetTasksRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/remotes/tasks",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
