/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.clientapi.pdm.models.PdmCfEnum
import com.clientapi.pdm.models.PdmError
import com.clientapi.pdm.models.PdmTimeframeEnum
import com.clientapi.pdm.models.RemotesRemoteCreateRemoteRequest
import com.clientapi.pdm.models.RemotesRemoteCreateRemoteResponse
import com.clientapi.pdm.models.RemotesRemoteDeleteRemoteResponse
import com.clientapi.pdm.models.RemotesRemoteGetConfigResponse
import com.clientapi.pdm.models.RemotesRemoteGetRemoteResponse
import com.clientapi.pdm.models.RemotesRemoteGetRemotesRemoteByIdResponse
import com.clientapi.pdm.models.RemotesRemoteGetRrddataResponse
import com.clientapi.pdm.models.RemotesRemoteGetVersionResponse
import com.clientapi.pdm.models.RemotesRemoteUpdateRemoteRequest
import com.clientapi.pdm.models.RemotesRemoteUpdateRemoteResponse

import com.squareup.moshi.Json

import com.clientapi.pdm.infrastructure.ApiClient
import com.clientapi.pdm.infrastructure.ApiResponse
import com.clientapi.pdm.infrastructure.ClientException
import com.clientapi.pdm.infrastructure.ClientError
import com.clientapi.pdm.infrastructure.ServerException
import com.clientapi.pdm.infrastructure.ServerError
import com.clientapi.pdm.infrastructure.MultiValueMap
import com.clientapi.pdm.infrastructure.PartConfig
import com.clientapi.pdm.infrastructure.RequestConfig
import com.clientapi.pdm.infrastructure.RequestMethod
import com.clientapi.pdm.infrastructure.ResponseType
import com.clientapi.pdm.infrastructure.Success
import com.clientapi.pdm.infrastructure.toMultiValue

open class RemotesRemoteApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8443/api2/json")
        }
    }

    /**
     * POST /remotes/remote
     * List all the remotes this instance is managing
     * List all the remotes this instance is managing.
     * @param remotesRemoteCreateRemoteRequest 
     * @return RemotesRemoteCreateRemoteResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun remotesRemoteCreateRemote(remotesRemoteCreateRemoteRequest: RemotesRemoteCreateRemoteRequest) : RemotesRemoteCreateRemoteResponse {
        val localVarResponse = remotesRemoteCreateRemoteWithHttpInfo(remotesRemoteCreateRemoteRequest = remotesRemoteCreateRemoteRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as RemotesRemoteCreateRemoteResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /remotes/remote
     * List all the remotes this instance is managing
     * List all the remotes this instance is managing.
     * @param remotesRemoteCreateRemoteRequest 
     * @return ApiResponse<RemotesRemoteCreateRemoteResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun remotesRemoteCreateRemoteWithHttpInfo(remotesRemoteCreateRemoteRequest: RemotesRemoteCreateRemoteRequest) : ApiResponse<RemotesRemoteCreateRemoteResponse?> {
        val localVariableConfig = remotesRemoteCreateRemoteRequestConfig(remotesRemoteCreateRemoteRequest = remotesRemoteCreateRemoteRequest)

        return request<RemotesRemoteCreateRemoteRequest, RemotesRemoteCreateRemoteResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation remotesRemoteCreateRemote
     *
     * @param remotesRemoteCreateRemoteRequest 
     * @return RequestConfig
     */
    fun remotesRemoteCreateRemoteRequestConfig(remotesRemoteCreateRemoteRequest: RemotesRemoteCreateRemoteRequest) : RequestConfig<RemotesRemoteCreateRemoteRequest> {
        val localVariableBody = remotesRemoteCreateRemoteRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/remotes/remote",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /remotes/remote/{id}
     * List all the remotes this instance is managing
     * List all the remotes this instance is managing.
     * @param id Remote ID.
     * @return RemotesRemoteDeleteRemoteResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun remotesRemoteDeleteRemote(id: kotlin.String) : RemotesRemoteDeleteRemoteResponse {
        val localVarResponse = remotesRemoteDeleteRemoteWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as RemotesRemoteDeleteRemoteResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /remotes/remote/{id}
     * List all the remotes this instance is managing
     * List all the remotes this instance is managing.
     * @param id Remote ID.
     * @return ApiResponse<RemotesRemoteDeleteRemoteResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun remotesRemoteDeleteRemoteWithHttpInfo(id: kotlin.String) : ApiResponse<RemotesRemoteDeleteRemoteResponse?> {
        val localVariableConfig = remotesRemoteDeleteRemoteRequestConfig(id = id)

        return request<Unit, RemotesRemoteDeleteRemoteResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation remotesRemoteDeleteRemote
     *
     * @param id Remote ID.
     * @return RequestConfig
     */
    fun remotesRemoteDeleteRemoteRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/remotes/remote/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /remotes/remote/{id}/config
     * Get the Remote Configuration
     * Get the Remote Configuration
     * @param id Remote ID.
     * @return RemotesRemoteGetConfigResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun remotesRemoteGetConfig(id: kotlin.String) : RemotesRemoteGetConfigResponse {
        val localVarResponse = remotesRemoteGetConfigWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as RemotesRemoteGetConfigResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /remotes/remote/{id}/config
     * Get the Remote Configuration
     * Get the Remote Configuration
     * @param id Remote ID.
     * @return ApiResponse<RemotesRemoteGetConfigResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun remotesRemoteGetConfigWithHttpInfo(id: kotlin.String) : ApiResponse<RemotesRemoteGetConfigResponse?> {
        val localVariableConfig = remotesRemoteGetConfigRequestConfig(id = id)

        return request<Unit, RemotesRemoteGetConfigResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation remotesRemoteGetConfig
     *
     * @param id Remote ID.
     * @return RequestConfig
     */
    fun remotesRemoteGetConfigRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/remotes/remote/{id}/config".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /remotes/remote
     * List all the remotes this instance is managing
     * List all the remotes this instance is managing.  Permissions: Returns the resources the user has access to.
     * @return RemotesRemoteGetRemoteResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun remotesRemoteGetRemote() : RemotesRemoteGetRemoteResponse {
        val localVarResponse = remotesRemoteGetRemoteWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as RemotesRemoteGetRemoteResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /remotes/remote
     * List all the remotes this instance is managing
     * List all the remotes this instance is managing.  Permissions: Returns the resources the user has access to.
     * @return ApiResponse<RemotesRemoteGetRemoteResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun remotesRemoteGetRemoteWithHttpInfo() : ApiResponse<RemotesRemoteGetRemoteResponse?> {
        val localVariableConfig = remotesRemoteGetRemoteRequestConfig()

        return request<Unit, RemotesRemoteGetRemoteResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation remotesRemoteGetRemote
     *
     * @return RequestConfig
     */
    fun remotesRemoteGetRemoteRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/remotes/remote",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /remotes/remote/{id}
     * Directory index
     * Directory index.
     * @param id 
     * @return RemotesRemoteGetRemotesRemoteByIdResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun remotesRemoteGetRemotesRemoteById(id: kotlin.String) : RemotesRemoteGetRemotesRemoteByIdResponse {
        val localVarResponse = remotesRemoteGetRemotesRemoteByIdWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as RemotesRemoteGetRemotesRemoteByIdResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /remotes/remote/{id}
     * Directory index
     * Directory index.
     * @param id 
     * @return ApiResponse<RemotesRemoteGetRemotesRemoteByIdResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun remotesRemoteGetRemotesRemoteByIdWithHttpInfo(id: kotlin.String) : ApiResponse<RemotesRemoteGetRemotesRemoteByIdResponse?> {
        val localVariableConfig = remotesRemoteGetRemotesRemoteByIdRequestConfig(id = id)

        return request<Unit, RemotesRemoteGetRemotesRemoteByIdResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation remotesRemoteGetRemotesRemoteById
     *
     * @param id 
     * @return RequestConfig
     */
    fun remotesRemoteGetRemotesRemoteByIdRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/remotes/remote/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /remotes/remote/{id}/rrddata
     * Read metric collection RRD data
     * Read metric collection RRD data.
     * @param id Remote ID.
     * @param cf RRD consolidation mode
     * @param timeframe RRD time frame
     * @return RemotesRemoteGetRrddataResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun remotesRemoteGetRrddata(id: kotlin.String, cf: PdmCfEnum, timeframe: PdmTimeframeEnum) : RemotesRemoteGetRrddataResponse {
        val localVarResponse = remotesRemoteGetRrddataWithHttpInfo(id = id, cf = cf, timeframe = timeframe)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as RemotesRemoteGetRrddataResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /remotes/remote/{id}/rrddata
     * Read metric collection RRD data
     * Read metric collection RRD data.
     * @param id Remote ID.
     * @param cf RRD consolidation mode
     * @param timeframe RRD time frame
     * @return ApiResponse<RemotesRemoteGetRrddataResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun remotesRemoteGetRrddataWithHttpInfo(id: kotlin.String, cf: PdmCfEnum, timeframe: PdmTimeframeEnum) : ApiResponse<RemotesRemoteGetRrddataResponse?> {
        val localVariableConfig = remotesRemoteGetRrddataRequestConfig(id = id, cf = cf, timeframe = timeframe)

        return request<Unit, RemotesRemoteGetRrddataResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation remotesRemoteGetRrddata
     *
     * @param id Remote ID.
     * @param cf RRD consolidation mode
     * @param timeframe RRD time frame
     * @return RequestConfig
     */
    fun remotesRemoteGetRrddataRequestConfig(id: kotlin.String, cf: PdmCfEnum, timeframe: PdmTimeframeEnum) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("cf", listOf(cf.toString()))
                put("timeframe", listOf(timeframe.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/remotes/remote/{id}/rrddata".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /remotes/remote/{id}/version
     * Query the remote&#39;s version
     * Query the remote&#39;s version.  FIXME: Should we add an option to explicitly query the entire cluster to get a full version overview?
     * @param id Remote ID.
     * @return RemotesRemoteGetVersionResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun remotesRemoteGetVersion(id: kotlin.String) : RemotesRemoteGetVersionResponse {
        val localVarResponse = remotesRemoteGetVersionWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as RemotesRemoteGetVersionResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /remotes/remote/{id}/version
     * Query the remote&#39;s version
     * Query the remote&#39;s version.  FIXME: Should we add an option to explicitly query the entire cluster to get a full version overview?
     * @param id Remote ID.
     * @return ApiResponse<RemotesRemoteGetVersionResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun remotesRemoteGetVersionWithHttpInfo(id: kotlin.String) : ApiResponse<RemotesRemoteGetVersionResponse?> {
        val localVariableConfig = remotesRemoteGetVersionRequestConfig(id = id)

        return request<Unit, RemotesRemoteGetVersionResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation remotesRemoteGetVersion
     *
     * @param id Remote ID.
     * @return RequestConfig
     */
    fun remotesRemoteGetVersionRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/remotes/remote/{id}/version".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /remotes/remote/{id}
     * List all the remotes this instance is managing
     * List all the remotes this instance is managing.
     * @param id Remote ID.
     * @param remotesRemoteUpdateRemoteRequest  (optional)
     * @return RemotesRemoteUpdateRemoteResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun remotesRemoteUpdateRemote(id: kotlin.String, remotesRemoteUpdateRemoteRequest: RemotesRemoteUpdateRemoteRequest? = null) : RemotesRemoteUpdateRemoteResponse {
        val localVarResponse = remotesRemoteUpdateRemoteWithHttpInfo(id = id, remotesRemoteUpdateRemoteRequest = remotesRemoteUpdateRemoteRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as RemotesRemoteUpdateRemoteResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /remotes/remote/{id}
     * List all the remotes this instance is managing
     * List all the remotes this instance is managing.
     * @param id Remote ID.
     * @param remotesRemoteUpdateRemoteRequest  (optional)
     * @return ApiResponse<RemotesRemoteUpdateRemoteResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun remotesRemoteUpdateRemoteWithHttpInfo(id: kotlin.String, remotesRemoteUpdateRemoteRequest: RemotesRemoteUpdateRemoteRequest?) : ApiResponse<RemotesRemoteUpdateRemoteResponse?> {
        val localVariableConfig = remotesRemoteUpdateRemoteRequestConfig(id = id, remotesRemoteUpdateRemoteRequest = remotesRemoteUpdateRemoteRequest)

        return request<RemotesRemoteUpdateRemoteRequest, RemotesRemoteUpdateRemoteResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation remotesRemoteUpdateRemote
     *
     * @param id Remote ID.
     * @param remotesRemoteUpdateRemoteRequest  (optional)
     * @return RequestConfig
     */
    fun remotesRemoteUpdateRemoteRequestConfig(id: kotlin.String, remotesRemoteUpdateRemoteRequest: RemotesRemoteUpdateRemoteRequest?) : RequestConfig<RemotesRemoteUpdateRemoteRequest> {
        val localVariableBody = remotesRemoteUpdateRemoteRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/remotes/remote/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
