/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.clientapi.pdm.models.PdmError
import com.clientapi.pdm.models.PdmTyEnum
import com.clientapi.pdm.models.SdnGetControllersResponse
import com.clientapi.pdm.models.SdnGetSdnResponse

import com.squareup.moshi.Json

import com.clientapi.pdm.infrastructure.ApiClient
import com.clientapi.pdm.infrastructure.ApiResponse
import com.clientapi.pdm.infrastructure.ClientException
import com.clientapi.pdm.infrastructure.ClientError
import com.clientapi.pdm.infrastructure.ServerException
import com.clientapi.pdm.infrastructure.ServerError
import com.clientapi.pdm.infrastructure.MultiValueMap
import com.clientapi.pdm.infrastructure.PartConfig
import com.clientapi.pdm.infrastructure.RequestConfig
import com.clientapi.pdm.infrastructure.RequestMethod
import com.clientapi.pdm.infrastructure.ResponseType
import com.clientapi.pdm.infrastructure.Success
import com.clientapi.pdm.infrastructure.toMultiValue

open class SdnApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8443/api2/json")
        }
    }

    /**
     * GET /sdn/controllers
     * Query controllers of remotes with optional filtering options
     * Query controllers of remotes with optional filtering options  Permissions: The user needs to have at least the &#x60;Resource.Audit&#x60; privilege under &#x60;/resource&#x60;.         Only controllers from remotes for which the user has &#x60;Resource.Audit&#x60; on &#x60;/resource/{remote_name}&#x60;         will be included in the returned list.
     * @param pending Include a list of attributes whose changes are currently pending. (optional)
     * @param remotes Only return controllers from the specified remotes. (optional)
     * @param running If true shows the running configuration, otherwise the pending configuration. (optional)
     * @param ty Only list sdn controllers of specific type (optional)
     * @return SdnGetControllersResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun sdnGetControllers(pending: kotlin.Boolean? = null, remotes: kotlin.collections.List<kotlin.String>? = null, running: kotlin.Boolean? = null, ty: PdmTyEnum? = null) : SdnGetControllersResponse {
        val localVarResponse = sdnGetControllersWithHttpInfo(pending = pending, remotes = remotes, running = running, ty = ty)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SdnGetControllersResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /sdn/controllers
     * Query controllers of remotes with optional filtering options
     * Query controllers of remotes with optional filtering options  Permissions: The user needs to have at least the &#x60;Resource.Audit&#x60; privilege under &#x60;/resource&#x60;.         Only controllers from remotes for which the user has &#x60;Resource.Audit&#x60; on &#x60;/resource/{remote_name}&#x60;         will be included in the returned list.
     * @param pending Include a list of attributes whose changes are currently pending. (optional)
     * @param remotes Only return controllers from the specified remotes. (optional)
     * @param running If true shows the running configuration, otherwise the pending configuration. (optional)
     * @param ty Only list sdn controllers of specific type (optional)
     * @return ApiResponse<SdnGetControllersResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun sdnGetControllersWithHttpInfo(pending: kotlin.Boolean?, remotes: kotlin.collections.List<kotlin.String>?, running: kotlin.Boolean?, ty: PdmTyEnum?) : ApiResponse<SdnGetControllersResponse?> {
        val localVariableConfig = sdnGetControllersRequestConfig(pending = pending, remotes = remotes, running = running, ty = ty)

        return request<Unit, SdnGetControllersResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation sdnGetControllers
     *
     * @param pending Include a list of attributes whose changes are currently pending. (optional)
     * @param remotes Only return controllers from the specified remotes. (optional)
     * @param running If true shows the running configuration, otherwise the pending configuration. (optional)
     * @param ty Only list sdn controllers of specific type (optional)
     * @return RequestConfig
     */
    fun sdnGetControllersRequestConfig(pending: kotlin.Boolean?, remotes: kotlin.collections.List<kotlin.String>?, running: kotlin.Boolean?, ty: PdmTyEnum?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (pending != null) {
                    put("pending", listOf(pending.toString()))
                }
                if (remotes != null) {
                    put("remotes", toMultiValue(remotes.toList(), "multi"))
                }
                if (running != null) {
                    put("running", listOf(running.toString()))
                }
                if (ty != null) {
                    put("ty", listOf(ty.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/sdn/controllers",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /sdn
     * Directory index
     * Directory index.
     * @return SdnGetSdnResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun sdnGetSdn() : SdnGetSdnResponse {
        val localVarResponse = sdnGetSdnWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SdnGetSdnResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /sdn
     * Directory index
     * Directory index.
     * @return ApiResponse<SdnGetSdnResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun sdnGetSdnWithHttpInfo() : ApiResponse<SdnGetSdnResponse?> {
        val localVariableConfig = sdnGetSdnRequestConfig()

        return request<Unit, SdnGetSdnResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation sdnGetSdn
     *
     * @return RequestConfig
     */
    fun sdnGetSdnRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/sdn",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
