/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.clientapi.pdm.models.PdmError
import com.clientapi.pdm.models.SdnVnetsCreateVnetsRequest
import com.clientapi.pdm.models.SdnVnetsCreateVnetsResponse
import com.clientapi.pdm.models.SdnVnetsGetVnetsResponse

import com.squareup.moshi.Json

import com.clientapi.pdm.infrastructure.ApiClient
import com.clientapi.pdm.infrastructure.ApiResponse
import com.clientapi.pdm.infrastructure.ClientException
import com.clientapi.pdm.infrastructure.ClientError
import com.clientapi.pdm.infrastructure.ServerException
import com.clientapi.pdm.infrastructure.ServerError
import com.clientapi.pdm.infrastructure.MultiValueMap
import com.clientapi.pdm.infrastructure.PartConfig
import com.clientapi.pdm.infrastructure.RequestConfig
import com.clientapi.pdm.infrastructure.RequestMethod
import com.clientapi.pdm.infrastructure.ResponseType
import com.clientapi.pdm.infrastructure.Success
import com.clientapi.pdm.infrastructure.toMultiValue

open class SdnVnetsApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8443/api2/json")
        }
    }

    /**
     * POST /sdn/vnets
     * Create a VNet across multiple remotes
     * Create a VNet across multiple remotes
     * @param sdnVnetsCreateVnetsRequest 
     * @return SdnVnetsCreateVnetsResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun sdnVnetsCreateVnets(sdnVnetsCreateVnetsRequest: SdnVnetsCreateVnetsRequest) : SdnVnetsCreateVnetsResponse {
        val localVarResponse = sdnVnetsCreateVnetsWithHttpInfo(sdnVnetsCreateVnetsRequest = sdnVnetsCreateVnetsRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SdnVnetsCreateVnetsResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /sdn/vnets
     * Create a VNet across multiple remotes
     * Create a VNet across multiple remotes
     * @param sdnVnetsCreateVnetsRequest 
     * @return ApiResponse<SdnVnetsCreateVnetsResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun sdnVnetsCreateVnetsWithHttpInfo(sdnVnetsCreateVnetsRequest: SdnVnetsCreateVnetsRequest) : ApiResponse<SdnVnetsCreateVnetsResponse?> {
        val localVariableConfig = sdnVnetsCreateVnetsRequestConfig(sdnVnetsCreateVnetsRequest = sdnVnetsCreateVnetsRequest)

        return request<SdnVnetsCreateVnetsRequest, SdnVnetsCreateVnetsResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation sdnVnetsCreateVnets
     *
     * @param sdnVnetsCreateVnetsRequest 
     * @return RequestConfig
     */
    fun sdnVnetsCreateVnetsRequestConfig(sdnVnetsCreateVnetsRequest: SdnVnetsCreateVnetsRequest) : RequestConfig<SdnVnetsCreateVnetsRequest> {
        val localVariableBody = sdnVnetsCreateVnetsRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/sdn/vnets",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /sdn/vnets
     * Query VNets of PVE remotes with optional filtering options
     * Query VNets of PVE remotes with optional filtering options  Permissions: The user needs to have at least the &#x60;Resource.Audit&#x60; privilege under &#x60;/resource&#x60;.         Only vnets from remotes for which the user has &#x60;Resource.Audit&#x60; on &#x60;/resource/{remote_name}&#x60;         will be included in the returned list.
     * @param pending Include a list of attributes whose changes are currently pending. (optional)
     * @param remotes Only return controllers from the specified remotes. (optional)
     * @param running If true shows the running configuration, otherwise the pending configuration. (optional)
     * @return SdnVnetsGetVnetsResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun sdnVnetsGetVnets(pending: kotlin.Boolean? = null, remotes: kotlin.collections.List<kotlin.String>? = null, running: kotlin.Boolean? = null) : SdnVnetsGetVnetsResponse {
        val localVarResponse = sdnVnetsGetVnetsWithHttpInfo(pending = pending, remotes = remotes, running = running)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SdnVnetsGetVnetsResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /sdn/vnets
     * Query VNets of PVE remotes with optional filtering options
     * Query VNets of PVE remotes with optional filtering options  Permissions: The user needs to have at least the &#x60;Resource.Audit&#x60; privilege under &#x60;/resource&#x60;.         Only vnets from remotes for which the user has &#x60;Resource.Audit&#x60; on &#x60;/resource/{remote_name}&#x60;         will be included in the returned list.
     * @param pending Include a list of attributes whose changes are currently pending. (optional)
     * @param remotes Only return controllers from the specified remotes. (optional)
     * @param running If true shows the running configuration, otherwise the pending configuration. (optional)
     * @return ApiResponse<SdnVnetsGetVnetsResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun sdnVnetsGetVnetsWithHttpInfo(pending: kotlin.Boolean?, remotes: kotlin.collections.List<kotlin.String>?, running: kotlin.Boolean?) : ApiResponse<SdnVnetsGetVnetsResponse?> {
        val localVariableConfig = sdnVnetsGetVnetsRequestConfig(pending = pending, remotes = remotes, running = running)

        return request<Unit, SdnVnetsGetVnetsResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation sdnVnetsGetVnets
     *
     * @param pending Include a list of attributes whose changes are currently pending. (optional)
     * @param remotes Only return controllers from the specified remotes. (optional)
     * @param running If true shows the running configuration, otherwise the pending configuration. (optional)
     * @return RequestConfig
     */
    fun sdnVnetsGetVnetsRequestConfig(pending: kotlin.Boolean?, remotes: kotlin.collections.List<kotlin.String>?, running: kotlin.Boolean?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (pending != null) {
                    put("pending", listOf(pending.toString()))
                }
                if (remotes != null) {
                    put("remotes", toMultiValue(remotes.toList(), "multi"))
                }
                if (running != null) {
                    put("running", listOf(running.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/sdn/vnets",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
