/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models

import com.clientapi.pdm.models.PdmAccessUsersInlineEnum2

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param comment Comment.
 * @param delete List of properties to delete.
 * @param digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
 * @param enable Enable the account (default). You can set this to '0' to disable the account.
 * @param expire Account expiration date (seconds since epoch). '0' means no expiration date.
 * @param regenerate Regenerate token secret while keeping permissions.
 */


data class AccessUsersUpdateTokenRequest (

    /* Comment. */
    @Json(name = "comment")
    val comment: kotlin.String? = null,

    /* List of properties to delete. */
    @Json(name = "delete")
    val delete: kotlin.collections.List<PdmAccessUsersInlineEnum2>? = null,

    /* Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications. */
    @Json(name = "digest")
    val digest: kotlin.String? = null,

    /* Enable the account (default). You can set this to '0' to disable the account. */
    @Json(name = "enable")
    val enable: kotlin.Boolean? = true,

    /* Account expiration date (seconds since epoch). '0' means no expiration date. */
    @Json(name = "expire")
    val expire: kotlin.Long? = 0L,

    /* Regenerate token secret while keeping permissions. */
    @Json(name = "regenerate")
    val regenerate: kotlin.Boolean? = false

) {


}

