/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models

import com.clientapi.pdm.models.PdmAccessAclUgidTypeEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param path Access control path.
 * @param propagate Allow to propagate (inherit) permissions.
 * @param roleid A role represented as a string.
 * @param ugid User or Group ID.
 * @param ugidType Type of the 'ugid' property in the ACL entry list.
 */


data class AccessAclGetAclResponseDataInner (

    /* Access control path. */
    @Json(name = "path")
    val path: kotlin.String,

    /* Allow to propagate (inherit) permissions. */
    @Json(name = "propagate")
    val propagate: kotlin.Boolean = true,

    /* A role represented as a string. */
    @Json(name = "roleid")
    val roleid: kotlin.String,

    /* User or Group ID. */
    @Json(name = "ugid")
    val ugid: kotlin.String,

    /* Type of the 'ugid' property in the ACL entry list. */
    @Json(name = "ugid_type")
    val ugidType: PdmAccessAclUgidTypeEnum

) {


}

