/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param recovery A list of recovery codes as integers.
 * @param challenge When adding u2f entries, this contains a challenge the user must respond to in order to finish the registration.
 * @param id The id if a newly added TFA entry.
 */


data class AccessTfaCreateTfaResponseData (

    /* A list of recovery codes as integers. */
    @Json(name = "recovery")
    val recovery: kotlin.collections.List<kotlin.Long>,

    /* When adding u2f entries, this contains a challenge the user must respond to in order to finish the registration. */
    @Json(name = "challenge")
    val challenge: kotlin.String? = null,

    /* The id if a newly added TFA entry. */
    @Json(name = "id")
    val id: kotlin.String? = null

) {


}

