/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param path Access control path.
 * @param role Name of a role that the auth id will be granted.
 * @param authId Authentication ID
 * @param delete Remove permissions (instead of adding it).
 * @param digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
 * @param group Group ID
 * @param propagate Allow to propagate (inherit) permissions.
 */


data class AccessAclUpdateAclRequest (

    /* Access control path. */
    @Json(name = "path")
    val path: kotlin.String,

    /* Name of a role that the auth id will be granted. */
    @Json(name = "role")
    val role: kotlin.String,

    /* Authentication ID */
    @Json(name = "auth-id")
    val authId: kotlin.String? = null,

    /* Remove permissions (instead of adding it). */
    @Json(name = "delete")
    val delete: kotlin.Boolean? = 0,

    /* Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications. */
    @Json(name = "digest")
    val digest: kotlin.String? = null,

    /* Group ID */
    @Json(name = "group")
    val group: kotlin.String? = null,

    /* Allow to propagate (inherit) permissions. */
    @Json(name = "propagate")
    val propagate: kotlin.Boolean? = 1

) {


}

