/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models

import com.clientapi.pdm.models.AccessUsersGetUsersResponseDataInnerTokensInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param userid User ID
 * @param comment Comment.
 * @param email E-Mail Address.
 * @param enable Enable the account (default). You can set this to '0' to disable the account.
 * @param expire Account expiration date (seconds since epoch). '0' means no expiration date.
 * @param firstname First name.
 * @param lastname Last name.
 * @param tfaLockedUntil Contains a timestamp until when a user is locked out of 2nd factors
 * @param tokens List of user's API tokens.
 * @param totpLocked True if the user is currently locked out of TOTP factors
 */


data class AccessUsersGetUsersResponseDataInner (

    /* User ID */
    @Json(name = "userid")
    val userid: kotlin.String,

    /* Comment. */
    @Json(name = "comment")
    val comment: kotlin.String? = null,

    /* E-Mail Address. */
    @Json(name = "email")
    val email: kotlin.String? = null,

    /* Enable the account (default). You can set this to '0' to disable the account. */
    @Json(name = "enable")
    val enable: kotlin.Boolean? = true,

    /* Account expiration date (seconds since epoch). '0' means no expiration date. */
    @Json(name = "expire")
    val expire: kotlin.Long? = 0L,

    /* First name. */
    @Json(name = "firstname")
    val firstname: kotlin.String? = null,

    /* Last name. */
    @Json(name = "lastname")
    val lastname: kotlin.String? = null,

    /* Contains a timestamp until when a user is locked out of 2nd factors */
    @Json(name = "tfa-locked-until")
    val tfaLockedUntil: kotlin.Long? = null,

    /* List of user's API tokens. */
    @Json(name = "tokens")
    val tokens: kotlin.collections.List<AccessUsersGetUsersResponseDataInnerTokensInner>? = null,

    /* True if the user is currently locked out of TOTP factors */
    @Json(name = "totp-locked")
    val totpLocked: kotlin.Boolean? = false

) {


}

