/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models

import com.clientapi.pdm.models.PdmTypeEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param created Creation time of this entry as unix epoch.
 * @param description User chosen description for this entry.
 * @param enable Whether this TFA entry is currently enabled.
 * @param id The id used to reference this entry.
 * @param type A TFA entry type.
 */


data class AccessTfaGetTfaResponseDataInnerEntriesInner (

    /* Creation time of this entry as unix epoch. */
    @Json(name = "created")
    val created: kotlin.Long,

    /* User chosen description for this entry. */
    @Json(name = "description")
    val description: kotlin.String,

    /* Whether this TFA entry is currently enabled. */
    @Json(name = "enable")
    val enable: kotlin.Boolean,

    /* The id used to reference this entry. */
    @Json(name = "id")
    val id: kotlin.String,

    /* A TFA entry type. */
    @Json(name = "type")
    val type: PdmTypeEnum

) {


}

