/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models

import com.clientapi.pdm.models.AccessTfaGetTfaResponseDataInnerEntriesInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param propertyEntries TFA entries.
 * @param totpLocked The user is locked out of TOTP authentication.
 * @param userid The user this entry belongs to.
 * @param tfaLockedUntil If a user's second factor is blocked, this contains the block's expiration time.
 */


data class AccessTfaGetTfaResponseDataInner (

    /* TFA entries. */
    @Json(name = "entries")
    val propertyEntries: kotlin.collections.List<AccessTfaGetTfaResponseDataInnerEntriesInner>,

    /* The user is locked out of TOTP authentication. */
    @Json(name = "totp-locked")
    val totpLocked: kotlin.Boolean,

    /* The user this entry belongs to. */
    @Json(name = "userid")
    val userid: kotlin.String,

    /* If a user's second factor is blocked, this contains the block's expiration time. */
    @Json(name = "tfa-locked-until")
    val tfaLockedUntil: kotlin.Long? = null

) {


}

