/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models

import com.clientapi.pdm.models.PdmDeleteEnum
import com.clientapi.pdm.models.PdmModeEnum
import com.clientapi.pdm.models.PdmSyncAttributesField
import com.clientapi.pdm.models.PdmSyncDefaultsOptionsField
import com.clientapi.pdm.models.PdmUserClassesField

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param baseDn LDAP Domain
 * @param bindDn LDAP Domain
 * @param capath CA certificate to use for the server. The path can point to either a file, or a directory. If it points to a file, the PEM-formatted X.509 certificate stored at the path will be added as a trusted certificate. If the path points to a directory, the directory replaces the system's default certificate store at `/etc/ssl/certs` - Every file in the directory will be loaded as a trusted certificate.
 * @param comment Comment.
 * @param default True if you want this to be the default realm selected on login.
 * @param delete List of properties to delete.
 * @param digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
 * @param filter Custom LDAP search filter for user sync
 * @param mode LDAP connection type
 * @param password LDAP bind password
 * @param port Port
 * @param server1 LDAP server address
 * @param server2 Fallback LDAP server address
 * @param syncAttributes Comma-separated list of key=value pairs for specifying which LDAP attributes map to which peat user field. For example, to map the LDAP attribute ``mail`` to peat's ``email``, write ``email=mail``.
 * @param syncDefaultsOptions sync defaults options
 * @param userAttr Username attribute. Used to map a ``userid`` to LDAP to an LDAP ``dn``.
 * @param userClasses Comma-separated list of allowed objectClass values for user synchronization. For instance, if ``user-classes`` is set to ``person,user``, then user synchronization will consider all LDAP entities where ``objectClass: person`` `or` ``objectClass: user``.
 * @param verify Verify server certificate
 */


data class ConfigAccessUpdateLdapRequest (

    /* LDAP Domain */
    @Json(name = "base-dn")
    val baseDn: kotlin.String? = null,

    /* LDAP Domain */
    @Json(name = "bind-dn")
    val bindDn: kotlin.String? = null,

    /* CA certificate to use for the server. The path can point to either a file, or a directory. If it points to a file, the PEM-formatted X.509 certificate stored at the path will be added as a trusted certificate. If the path points to a directory, the directory replaces the system's default certificate store at `/etc/ssl/certs` - Every file in the directory will be loaded as a trusted certificate. */
    @Json(name = "capath")
    val capath: kotlin.String? = null,

    /* Comment. */
    @Json(name = "comment")
    val comment: kotlin.String? = null,

    /* True if you want this to be the default realm selected on login. */
    @Json(name = "default")
    val default: kotlin.Boolean? = false,

    /* List of properties to delete. */
    @Json(name = "delete")
    val delete: kotlin.collections.List<PdmDeleteEnum>? = null,

    /* Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications. */
    @Json(name = "digest")
    val digest: kotlin.String? = null,

    /* Custom LDAP search filter for user sync */
    @Json(name = "filter")
    val filter: kotlin.String? = null,

    /* LDAP connection type */
    @Json(name = "mode")
    val mode: PdmModeEnum? = null,

    /* LDAP bind password */
    @Json(name = "password")
    val password: kotlin.String? = null,

    /* Port */
    @Json(name = "port")
    val port: kotlin.Int? = null,

    /* LDAP server address */
    @Json(name = "server1")
    val server1: kotlin.String? = null,

    /* Fallback LDAP server address */
    @Json(name = "server2")
    val server2: kotlin.String? = null,

    /* Comma-separated list of key=value pairs for specifying which LDAP attributes map to which peat user field. For example, to map the LDAP attribute ``mail`` to peat's ``email``, write ``email=mail``. */
    @Json(name = "sync-attributes")
    val syncAttributes: PdmSyncAttributesField? = null,

    /* sync defaults options */
    @Json(name = "sync-defaults-options")
    val syncDefaultsOptions: PdmSyncDefaultsOptionsField? = null,

    /* Username attribute. Used to map a ``userid`` to LDAP to an LDAP ``dn``. */
    @Json(name = "user-attr")
    val userAttr: kotlin.String? = null,

    /* Comma-separated list of allowed objectClass values for user synchronization. For instance, if ``user-classes`` is set to ``person,user``, then user synchronization will consider all LDAP entities where ``objectClass: person`` `or` ``objectClass: user``. */
    @Json(name = "user-classes")
    val userClasses: PdmUserClassesField? = null,

    /* Verify server certificate */
    @Json(name = "verify")
    val verify: kotlin.Boolean? = false

) {


}

