/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models

import com.clientapi.pdm.models.ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param account 
 * @param directory The ACME directory URL the account was created at.
 * @param location The account's own URL within the ACME directory.
 * @param tos The ToS URL, if the user agreed to one.
 */


data class ConfigAcmeGetConfigAcmeAccountByNameResponseData (

    @Json(name = "account")
    val account: ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount,

    /* The ACME directory URL the account was created at. */
    @Json(name = "directory")
    val directory: kotlin.String,

    /* The account's own URL within the ACME directory. */
    @Json(name = "location")
    val location: kotlin.String,

    /* The ToS URL, if the user agreed to one. */
    @Json(name = "tos")
    val tos: kotlin.String? = null

) {


}

