/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param contact List of email addresses.
 * @param directory The ACME Directory.
 * @param eabHmacKey HMAC Key for External Account Binding.
 * @param eabKid Key Identifier for External Account Binding.
 * @param name ACME account name.
 * @param tosUrl URL of CA TermsOfService - setting this indicates agreement.
 */


data class ConfigAcmeCreateAccountRequest (

    /* List of email addresses. */
    @Json(name = "contact")
    val contact: kotlin.String,

    /* The ACME Directory. */
    @Json(name = "directory")
    val directory: kotlin.String? = null,

    /* HMAC Key for External Account Binding. */
    @Json(name = "eab_hmac_key")
    val eabHmacKey: kotlin.String? = null,

    /* Key Identifier for External Account Binding. */
    @Json(name = "eab_kid")
    val eabKid: kotlin.String? = null,

    /* ACME account name. */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* URL of CA TermsOfService - setting this indicates agreement. */
    @Json(name = "tos_url")
    val tosUrl: kotlin.String? = null

) {


}

