/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id View name.
 * @param exclude List of filter rules.
 * @param include List of filter rules.
 * @param includeAll Include all resources by default.
 * @param layout The configured layout, encoded as json
 */


data class ConfigViewsGetConfigViewsByIdResponseData (

    /* View name. */
    @Json(name = "id")
    val id: kotlin.String,

    /* List of filter rules. */
    @Json(name = "exclude")
    val exclude: kotlin.collections.List<kotlin.String>? = null,

    /* List of filter rules. */
    @Json(name = "include")
    val include: kotlin.collections.List<kotlin.String>? = null,

    /* Include all resources by default. */
    @Json(name = "include-all")
    val includeAll: kotlin.Boolean? = null,

    /* The configured layout, encoded as json */
    @Json(name = "layout")
    val layout: kotlin.String? = null

) {


}

