/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id Relying party ID. Must be the domain name without protocol, port or location.  Changing this *will* break existing credentials.
 * @param rp Relying party name. Any text identifier.  Changing this *may* break existing credentials.
 * @param allowSubdomains If an `origin` is specified, this specifies whether subdomains should be considered valid as well.  May be changed at any time.  Defaults to `true`.
 * @param origin Site origin. Must be a `https://` URL (or `http://localhost`). Should contain the address users type in their browsers to access the web interface.  Changing this *may* break existing credentials.
 */


data class ConfigAccessGetWebauthnResponseData (

    /* Relying party ID. Must be the domain name without protocol, port or location.  Changing this *will* break existing credentials. */
    @Json(name = "id")
    val id: kotlin.String,

    /* Relying party name. Any text identifier.  Changing this *may* break existing credentials. */
    @Json(name = "rp")
    val rp: kotlin.String,

    /* If an `origin` is specified, this specifies whether subdomains should be considered valid as well.  May be changed at any time.  Defaults to `true`. */
    @Json(name = "allow-subdomains")
    val allowSubdomains: kotlin.Boolean? = null,

    /* Site origin. Must be a `https://` URL (or `http://localhost`). Should contain the address users type in their browsers to access the web interface.  Changing this *may* break existing credentials. */
    @Json(name = "origin")
    val origin: kotlin.String? = null

) {


}

