/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models

import com.clientapi.pdm.models.PdmConfigAcmeInlineEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param api DNS API Plugin Id.
 * @param `data` DNS plugin data (base64 encoded with padding).
 * @param delete List of properties to delete.
 * @param digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
 * @param disable Flag to disable the config.
 * @param validationDelay Extra delay in seconds to wait before requesting validation.  Allows to cope with long TTL of DNS records.
 */


data class ConfigAcmeUpdatePluginsRequest (

    /* DNS API Plugin Id. */
    @Json(name = "api")
    val api: kotlin.String? = null,

    /* DNS plugin data (base64 encoded with padding). */
    @Json(name = "data")
    val `data`: kotlin.String? = null,

    /* List of properties to delete. */
    @Json(name = "delete")
    val delete: kotlin.collections.List<PdmConfigAcmeInlineEnum>? = null,

    /* Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications. */
    @Json(name = "digest")
    val digest: kotlin.String? = null,

    /* Flag to disable the config. */
    @Json(name = "disable")
    val disable: kotlin.Boolean? = 0,

    /* Extra delay in seconds to wait before requesting validation.  Allows to cope with long TTL of DNS records. */
    @Json(name = "validation-delay")
    val validationDelay: kotlin.Int? = 30

) {


}

