/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models

import com.clientapi.pdm.models.PdmAcrValuesField
import com.clientapi.pdm.models.PdmScopesField

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param clientId OpenID Client ID
 * @param issuerUrl OpenID Issuer Url
 * @param realm Realm name.
 * @param acrValues OpenID ACR List
 * @param autocreate Automatically create users if they do not exist.
 * @param clientKey OpenID Client Key
 * @param comment Comment.
 * @param default True if you want this to be the default realm selected on login.
 * @param prompt OpenID Prompt
 * @param scopes OpenID Scope List
 * @param usernameClaim Use the value of this attribute/claim as unique user name. It is up to the identity provider to guarantee the uniqueness. The OpenID specification only guarantees that Subject ('sub') is unique. Also make sure that the user is not allowed to change that attribute by himself!
 */


data class ConfigAccessCreateOpenidRequest (

    /* OpenID Client ID */
    @Json(name = "client-id")
    val clientId: kotlin.String,

    /* OpenID Issuer Url */
    @Json(name = "issuer-url")
    val issuerUrl: kotlin.String,

    /* Realm name. */
    @Json(name = "realm")
    val realm: kotlin.String,

    /* OpenID ACR List */
    @Json(name = "acr-values")
    val acrValues: PdmAcrValuesField? = null,

    /* Automatically create users if they do not exist. */
    @Json(name = "autocreate")
    val autocreate: kotlin.Boolean? = false,

    /* OpenID Client Key */
    @Json(name = "client-key")
    val clientKey: kotlin.String? = null,

    /* Comment. */
    @Json(name = "comment")
    val comment: kotlin.String? = null,

    /* True if you want this to be the default realm selected on login. */
    @Json(name = "default")
    val default: kotlin.Boolean? = null,

    /* OpenID Prompt */
    @Json(name = "prompt")
    val prompt: kotlin.String? = null,

    /* OpenID Scope List */
    @Json(name = "scopes")
    val scopes: PdmScopesField? = null,

    /* Use the value of this attribute/claim as unique user name. It is up to the identity provider to guarantee the uniqueness. The OpenID specification only guarantees that Subject ('sub') is unique. Also make sure that the user is not allowed to change that attribute by himself! */
    @Json(name = "username-claim")
    val usernameClaim: kotlin.String? = null

) {


}

