/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id Plugin ID.
 * @param name Human readable name, falls back to id.
 * @param schema The plugin's parameter schema.
 * @param type Plugin Type.
 */


data class ConfigAcmeGetChallengeSchemaResponseDataInner (

    /* Plugin ID. */
    @Json(name = "id")
    val id: kotlin.String,

    /* Human readable name, falls back to id. */
    @Json(name = "name")
    val name: kotlin.String,

    /* The plugin's parameter schema. */
    @Json(name = "schema")
    val schema: kotlin.Any,

    /* Plugin Type. */
    @Json(name = "type")
    val type: kotlin.String

) {


}

