/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Storage space usage information.
 *
 * @param avail Available space (bytes).
 * @param total Total space (bytes).
 * @param used Used space (bytes).
 */


data class NodesStatusGetStatusResponseDataRoot (

    /* Available space (bytes). */
    @Json(name = "avail")
    val avail: kotlin.Long,

    /* Total space (bytes). */
    @Json(name = "total")
    val total: kotlin.Long,

    /* Used space (bytes). */
    @Json(name = "used")
    val used: kotlin.Long

) {


}

