/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models

import com.clientapi.pdm.models.PdmStatusEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param status Subscription status
 * @param checktime timestamp of the last check done
 * @param key the subscription key, if set and permitted to access
 * @param message a more human readable status message
 * @param nextduedate next due date of the set subscription
 * @param productname human readable productname of the set subscription
 * @param regdate register date of the set subscription
 * @param serverid the server ID, if permitted to access
 * @param signature Signature for offline keys
 * @param url URL to the web shop
 */


data class NodesSubscriptionGetSubscriptionResponseData (

    /* Subscription status */
    @Json(name = "status")
    val status: PdmStatusEnum,

    /* timestamp of the last check done */
    @Json(name = "checktime")
    val checktime: kotlin.Long? = null,

    /* the subscription key, if set and permitted to access */
    @Json(name = "key")
    val key: kotlin.String? = null,

    /* a more human readable status message */
    @Json(name = "message")
    val message: kotlin.String? = null,

    /* next due date of the set subscription */
    @Json(name = "nextduedate")
    val nextduedate: kotlin.String? = null,

    /* human readable productname of the set subscription */
    @Json(name = "productname")
    val productname: kotlin.String? = null,

    /* register date of the set subscription */
    @Json(name = "regdate")
    val regdate: kotlin.String? = null,

    /* the server ID, if permitted to access */
    @Json(name = "serverid")
    val serverid: kotlin.String? = null,

    /* Signature for offline keys */
    @Json(name = "signature")
    val signature: kotlin.String? = null,

    /* URL to the web shop */
    @Json(name = "url")
    val url: kotlin.String? = null

) {


}

