/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param time Timestamp (UNIX epoch)
 * @param totalTime Total time in milliseconds needed for full metric collection run.
 */


data class NodesGetRrdataResponseDataInner (

    /* Timestamp (UNIX epoch) */
    @Json(name = "time")
    val time: kotlin.Long,

    /* Total time in milliseconds needed for full metric collection run. */
    @Json(name = "total-time")
    val totalTime: java.math.BigDecimal? = null

) {


}

