/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models

import com.clientapi.pdm.models.PdmBondModeEnum
import com.clientapi.pdm.models.PdmBondXmitHashPolicyEnum
import com.clientapi.pdm.models.PdmMethodEnum
import com.clientapi.pdm.models.PdmNodesNetworkTypeEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param active Interface is active (UP)
 * @param altnames List of altnames for this interface
 * @param autostart Autostart interface
 * @param name Network interface name.
 * @param options Option list (inet)
 * @param options6 Option list (inet6)
 * @param type Network interface type
 * @param bondPrimary Network interface name.
 * @param bondMode Linux Bond Mode
 * @param bondXmitHashPolicy Bond Transmit Hash Policy for LACP (802.3ad)
 * @param bridgePorts Network interface list.
 * @param bridgeVlanAware Enable bridge vlan support.
 * @param cidr IPv4 address with netmask (CIDR notation).
 * @param cidr6 IPv6 address with netmask (CIDR notation).
 * @param comments Comments (inet, may span multiple lines)
 * @param comments6 Comments (inet6, may span multiple lines)
 * @param gateway IPv4 address.
 * @param gateway6 IPv6 address.
 * @param method Interface configuration method
 * @param method6 Interface configuration method
 * @param mtu Maximum Transmission Unit
 * @param slaves Network interface list.
 * @param vlanId VLAN ID.
 * @param vlanRawDevice Network interface name.
 */


data class NodesNetworkGetNetworkResponseDataInner (

    /* Interface is active (UP) */
    @Json(name = "active")
    val active: kotlin.Boolean,

    /* List of altnames for this interface */
    @Json(name = "altnames")
    val altnames: kotlin.collections.List<kotlin.String>,

    /* Autostart interface */
    @Json(name = "autostart")
    val autostart: kotlin.Boolean,

    /* Network interface name. */
    @Json(name = "name")
    val name: kotlin.String,

    /* Option list (inet) */
    @Json(name = "options")
    val options: kotlin.collections.List<kotlin.String>,

    /* Option list (inet6) */
    @Json(name = "options6")
    val options6: kotlin.collections.List<kotlin.String>,

    /* Network interface type */
    @Json(name = "type")
    val type: PdmNodesNetworkTypeEnum,

    /* Network interface name. */
    @Json(name = "bond-primary")
    val bondPrimary: kotlin.String? = null,

    /* Linux Bond Mode */
    @Json(name = "bond_mode")
    val bondMode: PdmBondModeEnum? = null,

    /* Bond Transmit Hash Policy for LACP (802.3ad) */
    @Json(name = "bond_xmit_hash_policy")
    val bondXmitHashPolicy: PdmBondXmitHashPolicyEnum? = null,

    /* Network interface list. */
    @Json(name = "bridge_ports")
    val bridgePorts: kotlin.collections.List<kotlin.String>? = null,

    /* Enable bridge vlan support. */
    @Json(name = "bridge_vlan_aware")
    val bridgeVlanAware: kotlin.Boolean? = null,

    /* IPv4 address with netmask (CIDR notation). */
    @Json(name = "cidr")
    val cidr: kotlin.String? = null,

    /* IPv6 address with netmask (CIDR notation). */
    @Json(name = "cidr6")
    val cidr6: kotlin.String? = null,

    /* Comments (inet, may span multiple lines) */
    @Json(name = "comments")
    val comments: kotlin.String? = null,

    /* Comments (inet6, may span multiple lines) */
    @Json(name = "comments6")
    val comments6: kotlin.String? = null,

    /* IPv4 address. */
    @Json(name = "gateway")
    val gateway: kotlin.String? = null,

    /* IPv6 address. */
    @Json(name = "gateway6")
    val gateway6: kotlin.String? = null,

    /* Interface configuration method */
    @Json(name = "method")
    val method: PdmMethodEnum? = null,

    /* Interface configuration method */
    @Json(name = "method6")
    val method6: PdmMethodEnum? = null,

    /* Maximum Transmission Unit */
    @Json(name = "mtu")
    val mtu: kotlin.Long? = null,

    /* Network interface list. */
    @Json(name = "slaves")
    val slaves: kotlin.collections.List<kotlin.String>? = null,

    /* VLAN ID. */
    @Json(name = "vlan-id")
    val vlanId: kotlin.Long? = null,

    /* Network interface name. */
    @Json(name = "vlan-raw-device")
    val vlanRawDevice: kotlin.String? = null

) {


}

