/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param key Option key.
 * @param propertyValues Option values.
 */


data class NodesAptGetRepositoriesResponseDataFilesInnerRepositoriesInnerOptionsInner (

    /* Option key. */
    @Json(name = "Key")
    val key: kotlin.String,

    /* Option values. */
    @Json(name = "Values")
    val propertyValues: kotlin.collections.List<kotlin.String>

) {


}

