/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param index Index of the associated repository within the file (starting from 0).
 * @param kind Info kind (e.g. \"warning\")
 * @param message Info message
 * @param path Path to the defining file.
 * @param `property` The property from which the info originates (e.g. \"Suites\")
 */


data class NodesAptGetRepositoriesResponseDataInfosInner (

    /* Index of the associated repository within the file (starting from 0). */
    @Json(name = "index")
    val index: kotlin.Long,

    /* Info kind (e.g. \"warning\") */
    @Json(name = "kind")
    val kind: kotlin.String,

    /* Info message */
    @Json(name = "message")
    val message: kotlin.String,

    /* Path to the defining file. */
    @Json(name = "path")
    val path: kotlin.String,

    /* The property from which the info originates (e.g. \"Suites\") */
    @Json(name = "property")
    val `property`: kotlin.String? = null

) {


}

