/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Node memory usage counters
 *
 * @param free Free memory
 * @param total Total memory
 * @param used Used memory
 */


data class NodesStatusGetStatusResponseDataMemory (

    /* Free memory */
    @Json(name = "free")
    val free: kotlin.Long,

    /* Total memory */
    @Json(name = "total")
    val total: kotlin.Long,

    /* Used memory */
    @Json(name = "used")
    val used: kotlin.Long

) {


}

