/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param port 
 * @param ticket 
 * @param upid 
 * @param user 
 */


data class NodesCreateTermproxyResponseData (

    @Json(name = "port")
    val port: kotlin.String,

    @Json(name = "ticket")
    val ticket: kotlin.String,

    @Json(name = "upid")
    val upid: kotlin.String,

    @Json(name = "user")
    val user: kotlin.String

) {


}

