/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models

import com.clientapi.pdm.models.NodesAptGetRepositoriesResponseDataFilesInnerRepositoriesInnerOptionsInner
import com.clientapi.pdm.models.PdmFileTypeEnum
import com.clientapi.pdm.models.PdmNodesAptInlineEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param components List of repository components.
 * @param enabled Whether the repository is enabled or not.
 * @param fileType The type of format used for an APT repository.
 * @param suites List of distributions.
 * @param types List of package types.
 * @param urIs List of repository URIs.
 * @param comment Associated comment.
 * @param options Additional options.
 */


data class NodesAptGetRepositoriesResponseDataFilesInnerRepositoriesInner (

    /* List of repository components. */
    @Json(name = "Components")
    val components: kotlin.collections.List<kotlin.String>,

    /* Whether the repository is enabled or not. */
    @Json(name = "Enabled")
    val enabled: kotlin.Boolean,

    /* The type of format used for an APT repository. */
    @Json(name = "FileType")
    val fileType: PdmFileTypeEnum,

    /* List of distributions. */
    @Json(name = "Suites")
    val suites: kotlin.collections.List<kotlin.String>,

    /* List of package types. */
    @Json(name = "Types")
    val types: kotlin.collections.List<PdmNodesAptInlineEnum>,

    /* List of repository URIs. */
    @Json(name = "URIs")
    val urIs: kotlin.collections.List<kotlin.String>,

    /* Associated comment. */
    @Json(name = "Comment")
    val comment: kotlin.String? = null,

    /* Additional options. */
    @Json(name = "Options")
    val options: kotlin.collections.List<NodesAptGetRepositoriesResponseDataFilesInnerRepositoriesInnerOptionsInner>? = null

) {


}

