/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param hostname Hostname (with optional port) of the target remote
 * @param fingerprint Fingerprint of the target remote.
 */


data class PbsCreateProbeTlsRequest (

    /* Hostname (with optional port) of the target remote */
    @Json(name = "hostname")
    val hostname: kotlin.String,

    /* Fingerprint of the target remote. */
    @Json(name = "fingerprint")
    val fingerprint: kotlin.String? = null

) {


}

