/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models

import com.clientapi.pdm.models.PdmPbsRemotesStatusEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param node Node the task is running on.
 * @param pid The Unix PID
 * @param pstart The task start time (Epoch)
 * @param starttime The task's start time.
 * @param status Whether a task is still running.
 * @param type The task type.
 * @param upid The task's UPID.
 * @param user The authenticated entity who started the task.
 * @param exitstatus Exit status, if available.
 * @param id Task id.
 */


data class PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData (

    /* Node the task is running on. */
    @Json(name = "node")
    val node: kotlin.String,

    /* The Unix PID */
    @Json(name = "pid")
    val pid: kotlin.Long,

    /* The task start time (Epoch) */
    @Json(name = "pstart")
    val pstart: kotlin.Long,

    /* The task's start time. */
    @Json(name = "starttime")
    val starttime: kotlin.Long,

    /* Whether a task is still running. */
    @Json(name = "status")
    val status: PdmPbsRemotesStatusEnum,

    /* The task type. */
    @Json(name = "type")
    val type: kotlin.String,

    /* The task's UPID. */
    @Json(name = "upid")
    val upid: kotlin.String,

    /* The authenticated entity who started the task. */
    @Json(name = "user")
    val user: kotlin.String,

    /* Exit status, if available. */
    @Json(name = "exitstatus")
    val exitstatus: kotlin.String? = null,

    /* Task id. */
    @Json(name = "id")
    val id: kotlin.String? = null

) {


}

