/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param ns Namespace.
 * @param comment The first line from the namespace's \"notes\"
 */


data class PbsRemotesGetNamespacesResponseDataInner (

    /* Namespace. */
    @Json(name = "ns")
    val ns: kotlin.String,

    /* The first line from the namespace's \"notes\" */
    @Json(name = "comment")
    val comment: kotlin.String? = null

) {


}

