/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models

import com.clientapi.pdm.models.PdmMaintenanceModeField
import com.clientapi.pdm.models.PdmNotifyField
import com.clientapi.pdm.models.PdmPbsRemotesNotificationModeEnum
import com.clientapi.pdm.models.PdmTuningField

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name Datastore name.
 * @param path Either the absolute path to the datastore directory, or a relative on-device path for removable datastores.
 * @param backend Datastore backend config
 * @param backingDevice The UUID of the filesystem partition for removable datastores.
 * @param comment Comment.
 * @param gcSchedule Run garbage collection job at specified schedule.
 * @param keepDaily Number of daily backups to keep.
 * @param keepHourly Number of hourly backups to keep.
 * @param keepLast Number of backups to keep.
 * @param keepMonthly Number of monthly backups to keep.
 * @param keepWeekly Number of weekly backups to keep.
 * @param keepYearly Number of yearly backups to keep.
 * @param maintenanceMode Maintenance mode, type is either 'offline' or 'read-only', message should be enclosed in \"
 * @param notificationMode Configure how notifications for this datastore should be sent. `legacy-sendmail` sends email notifications to the user configured in `notify-user` via the system's `sendmail` executable. `notification-system` emits matchable notification events to the notification system.
 * @param notify Datastore notification setting, enum can be one of 'always', 'never', or 'error'.
 * @param notifyUser User ID
 * @param pruneSchedule Run prune job at specified schedule.
 * @param tuning Datastore tuning options
 * @param verifyNew If enabled, all new backups will be verified right after completion.
 */


data class PbsRemotesGetDatastoreResponseDataInner (

    /* Datastore name. */
    @Json(name = "name")
    val name: kotlin.String,

    /* Either the absolute path to the datastore directory, or a relative on-device path for removable datastores. */
    @Json(name = "path")
    val path: kotlin.String,

    /* Datastore backend config */
    @Json(name = "backend")
    val backend: kotlin.String? = null,

    /* The UUID of the filesystem partition for removable datastores. */
    @Json(name = "backing-device")
    val backingDevice: kotlin.String? = null,

    /* Comment. */
    @Json(name = "comment")
    val comment: kotlin.String? = null,

    /* Run garbage collection job at specified schedule. */
    @Json(name = "gc-schedule")
    val gcSchedule: kotlin.String? = null,

    /* Number of daily backups to keep. */
    @Json(name = "keep-daily")
    val keepDaily: kotlin.Long? = null,

    /* Number of hourly backups to keep. */
    @Json(name = "keep-hourly")
    val keepHourly: kotlin.Long? = null,

    /* Number of backups to keep. */
    @Json(name = "keep-last")
    val keepLast: kotlin.Long? = null,

    /* Number of monthly backups to keep. */
    @Json(name = "keep-monthly")
    val keepMonthly: kotlin.Long? = null,

    /* Number of weekly backups to keep. */
    @Json(name = "keep-weekly")
    val keepWeekly: kotlin.Long? = null,

    /* Number of yearly backups to keep. */
    @Json(name = "keep-yearly")
    val keepYearly: kotlin.Long? = null,

    /* Maintenance mode, type is either 'offline' or 'read-only', message should be enclosed in \" */
    @Json(name = "maintenance-mode")
    val maintenanceMode: PdmMaintenanceModeField? = null,

    /* Configure how notifications for this datastore should be sent. `legacy-sendmail` sends email notifications to the user configured in `notify-user` via the system's `sendmail` executable. `notification-system` emits matchable notification events to the notification system. */
    @Json(name = "notification-mode")
    val notificationMode: PdmPbsRemotesNotificationModeEnum? = null,

    /* Datastore notification setting, enum can be one of 'always', 'never', or 'error'. */
    @Json(name = "notify")
    val notify: PdmNotifyField? = null,

    /* User ID */
    @Json(name = "notify-user")
    val notifyUser: kotlin.String? = null,

    /* Run prune job at specified schedule. */
    @Json(name = "prune-schedule")
    val pruneSchedule: kotlin.String? = null,

    /* Datastore tuning options */
    @Json(name = "tuning")
    val tuning: PdmTuningField? = null,

    /* If enabled, all new backups will be verified right after completion. */
    @Json(name = "verify-new")
    val verifyNew: kotlin.Boolean? = null

) {


}

