/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param description 
 * @param items OpenID Authentication Context Class Reference.
 * @param type 
 */


data class PdmAcrValuesConfig (

    @Json(name = "description")
    val description: kotlin.Any?,

    /* OpenID Authentication Context Class Reference. */
    @Json(name = "items")
    val items: kotlin.String,

    @Json(name = "type")
    val type: kotlin.Any?

) {


}

