/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: ACME,ACMEDOMAIN0,ACMEDOMAIN1,ACMEDOMAIN2,ACMEDOMAIN3,ACMEDOMAIN4
 */

@JsonClass(generateAdapter = false)
enum class PdmConfigCertificateInlineEnum(val value: kotlin.String) {

    @Json(name = "acme")
    ACME("acme"),

    @Json(name = "acmedomain0")
    ACMEDOMAIN0("acmedomain0"),

    @Json(name = "acmedomain1")
    ACMEDOMAIN1("acmedomain1"),

    @Json(name = "acmedomain2")
    ACMEDOMAIN2("acmedomain2"),

    @Json(name = "acmedomain3")
    ACMEDOMAIN3("acmedomain3"),

    @Json(name = "acmedomain4")
    ACMEDOMAIN4("acmedomain4");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is PdmConfigCertificateInlineEnum) "$data" else null

        /**
         * Returns a valid [PdmConfigCertificateInlineEnum] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): PdmConfigCertificateInlineEnum? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

