/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: EMERG,ALERT,CRIT,ERR,WARNING,NOTICE,INFO,DEBUG,NOLOG
 */

@JsonClass(generateAdapter = false)
enum class PdmLogLevelInEnum(val value: kotlin.String) {

    @Json(name = "emerg")
    EMERG("emerg"),

    @Json(name = "alert")
    ALERT("alert"),

    @Json(name = "crit")
    CRIT("crit"),

    @Json(name = "err")
    ERR("err"),

    @Json(name = "warning")
    WARNING("warning"),

    @Json(name = "notice")
    NOTICE("notice"),

    @Json(name = "info")
    INFO("info"),

    @Json(name = "debug")
    DEBUG("debug"),

    @Json(name = "nolog")
    NOLOG("nolog");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is PdmLogLevelInEnum) "$data" else null

        /**
         * Returns a valid [PdmLogLevelInEnum] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): PdmLogLevelInEnum? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

