/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: HTTP_PROXY,EMAIL_FROM,CIPHERS_TLS_1_PERIOD3,CIPHERS_TLS_1_PERIOD2,DEFAULT_LANG
 */

@JsonClass(generateAdapter = false)
enum class PdmNodesConfigInlineEnum(val value: kotlin.String) {

    @Json(name = "http-proxy")
    HTTP_PROXY("http-proxy"),

    @Json(name = "email-from")
    EMAIL_FROM("email-from"),

    @Json(name = "ciphers-tls-1.3")
    CIPHERS_TLS_1_PERIOD3("ciphers-tls-1.3"),

    @Json(name = "ciphers-tls-1.2")
    CIPHERS_TLS_1_PERIOD2("ciphers-tls-1.2"),

    @Json(name = "default-lang")
    DEFAULT_LANG("default-lang");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is PdmNodesConfigInlineEnum) "$data" else null

        /**
         * Returns a valid [PdmNodesConfigInlineEnum] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): PdmNodesConfigInlineEnum? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

