/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: CIDR,CIDR6,GATEWAY,GATEWAY6,METHOD,METHOD6,COMMENTS,COMMENTS6,MTU,AUTOSTART,BRIDGE_PORTS,BRIDGE_VLAN_AWARE,SLAVES,BOND_PRIMARY,BOND_XMIT_HASH_POLICY
 */

@JsonClass(generateAdapter = false)
enum class PdmNodesNetworkInlineEnum(val value: kotlin.String) {

    @Json(name = "cidr")
    CIDR("cidr"),

    @Json(name = "cidr6")
    CIDR6("cidr6"),

    @Json(name = "gateway")
    GATEWAY("gateway"),

    @Json(name = "gateway6")
    GATEWAY6("gateway6"),

    @Json(name = "method")
    METHOD("method"),

    @Json(name = "method6")
    METHOD6("method6"),

    @Json(name = "comments")
    COMMENTS("comments"),

    @Json(name = "comments6")
    COMMENTS6("comments6"),

    @Json(name = "mtu")
    MTU("mtu"),

    @Json(name = "autostart")
    AUTOSTART("autostart"),

    @Json(name = "bridge_ports")
    BRIDGE_PORTS("bridge_ports"),

    @Json(name = "bridge_vlan_aware")
    BRIDGE_VLAN_AWARE("bridge_vlan_aware"),

    @Json(name = "slaves")
    SLAVES("slaves"),

    @Json(name = "bond-primary")
    BOND_PRIMARY("bond-primary"),

    @Json(name = "bond_xmit_hash_policy")
    BOND_XMIT_HASH_POLICY("bond_xmit_hash_policy");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is PdmNodesNetworkInlineEnum) "$data" else null

        /**
         * Returns a valid [PdmNodesNetworkInlineEnum] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): PdmNodesNetworkInlineEnum? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

