/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: OTHER,WXP,W2K,W2K3,W2K8,WVISTA,WIN7,WIN8,WIN10,WIN11,L24,L26,SOLARIS
 */

@JsonClass(generateAdapter = false)
enum class PdmPveRemotesOstypeEnum2(val value: kotlin.String) {

    @Json(name = "other")
    OTHER("other"),

    @Json(name = "wxp")
    WXP("wxp"),

    @Json(name = "w2k")
    W2K("w2k"),

    @Json(name = "w2k3")
    W2K3("w2k3"),

    @Json(name = "w2k8")
    W2K8("w2k8"),

    @Json(name = "wvista")
    WVISTA("wvista"),

    @Json(name = "win7")
    WIN7("win7"),

    @Json(name = "win8")
    WIN8("win8"),

    @Json(name = "win10")
    WIN10("win10"),

    @Json(name = "win11")
    WIN11("win11"),

    @Json(name = "l24")
    L24("l24"),

    @Json(name = "l26")
    L26("l26"),

    @Json(name = "solaris")
    SOLARIS("solaris");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is PdmPveRemotesOstypeEnum2) "$data" else null

        /**
         * Returns a valid [PdmPveRemotesOstypeEnum2] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): PdmPveRemotesOstypeEnum2? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

