/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: LSI,LSI53C810,VIRTIO_SCSI_PCI,VIRTIO_SCSI_SINGLE,MEGASAS,PVSCSI
 */

@JsonClass(generateAdapter = false)
enum class PdmPveRemotesScsihwEnum(val value: kotlin.String) {

    @Json(name = "lsi")
    LSI("lsi"),

    @Json(name = "lsi53c810")
    LSI53C810("lsi53c810"),

    @Json(name = "virtio-scsi-pci")
    VIRTIO_SCSI_PCI("virtio-scsi-pci"),

    @Json(name = "virtio-scsi-single")
    VIRTIO_SCSI_SINGLE("virtio-scsi-single"),

    @Json(name = "megasas")
    MEGASAS("megasas"),

    @Json(name = "pvscsi")
    PVSCSI("pvscsi");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is PdmPveRemotesScsihwEnum) "$data" else null

        /**
         * Returns a valid [PdmPveRemotesScsihwEnum] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): PdmPveRemotesScsihwEnum? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

