/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: BACKUP,IMAGES,IMPORT,ISO,NONE,ROOTDIR,SNIPPETS,VZTMPL
 */

@JsonClass(generateAdapter = false)
enum class PdmPveRemotesItemsEnum(val value: kotlin.String) {

    @Json(name = "backup")
    BACKUP("backup"),

    @Json(name = "images")
    IMAGES("images"),

    @Json(name = "import")
    IMPORT("import"),

    @Json(name = "iso")
    ISO("iso"),

    @Json(name = "none")
    NONE("none"),

    @Json(name = "rootdir")
    ROOTDIR("rootdir"),

    @Json(name = "snippets")
    SNIPPETS("snippets"),

    @Json(name = "vztmpl")
    VZTMPL("vztmpl");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is PdmPveRemotesItemsEnum) "$data" else null

        /**
         * Returns a valid [PdmPveRemotesItemsEnum] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): PdmPveRemotesItemsEnum? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

