/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: EVPN,FAUCET,QINQ,SIMPLE,VLAN,VXLAN
 */

@JsonClass(generateAdapter = false)
enum class PdmSdnZonesTyEnum(val value: kotlin.String) {

    @Json(name = "evpn")
    EVPN("evpn"),

    @Json(name = "faucet")
    FAUCET("faucet"),

    @Json(name = "qinq")
    QINQ("qinq"),

    @Json(name = "simple")
    SIMPLE("simple"),

    @Json(name = "vlan")
    VLAN("vlan"),

    @Json(name = "vxlan")
    VXLAN("vxlan");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is PdmSdnZonesTyEnum) "$data" else null

        /**
         * Returns a valid [PdmSdnZonesTyEnum] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): PdmSdnZonesTyEnum? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

