/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Firewall status.
 *
 * @param active The amount of enabled rules
 * @param all The total amount of rules present
 * @param enabled True if the firewall is enabled
 */


data class PveFirewallGetStatusResponseDataInnerNodesInnerGuestsInnerStatus (

    /* The amount of enabled rules */
    @Json(name = "active")
    val active: kotlin.Long,

    /* The total amount of rules present */
    @Json(name = "all")
    val all: kotlin.Long,

    /* True if the firewall is enabled */
    @Json(name = "enabled")
    val enabled: kotlin.Boolean

) {


}

