/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models

import com.clientapi.pdm.models.PveRemotesGetMigrateResponseDataLocalDisksInner
import com.clientapi.pdm.models.PveRemotesGetMigrateResponseDataNotAllowedNodes

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param localDisks List local disks including CD-Rom, unused and not referenced disks
 * @param localResources List local resources (e.g. pci, usb) that block migration.
 * @param mappedResourceInfo Object of mapped resources with additional information such if they're live migratable.
 * @param mappedResources List of mapped resources e.g. pci, usb. Deprecated, use 'mapped-resource-info' instead.
 * @param running Determines if the VM is running.
 * @param allowedNodes List of nodes allowed for migration.
 * @param dependentHaResources HA resources, which will be migrated to the same target node as the VM, because these are in positive affinity with the VM.
 * @param hasDbusVmstate Whether the VM host supports migrating additional VM state, such as conntrack entries.
 * @param notAllowedNodes 
 */


data class PveRemotesGetMigrateResponseData (

    /* List local disks including CD-Rom, unused and not referenced disks */
    @Json(name = "local_disks")
    val localDisks: kotlin.collections.List<PveRemotesGetMigrateResponseDataLocalDisksInner>,

    /* List local resources (e.g. pci, usb) that block migration. */
    @Json(name = "local_resources")
    val localResources: kotlin.collections.List<kotlin.String>,

    /* Object of mapped resources with additional information such if they're live migratable. */
    @Json(name = "mapped-resource-info")
    val mappedResourceInfo: kotlin.Any,

    /* List of mapped resources e.g. pci, usb. Deprecated, use 'mapped-resource-info' instead. */
    @Json(name = "mapped-resources")
    val mappedResources: kotlin.collections.List<kotlin.String>,

    /* Determines if the VM is running. */
    @Json(name = "running")
    val running: kotlin.Boolean = false,

    /* List of nodes allowed for migration. */
    @Json(name = "allowed_nodes")
    val allowedNodes: kotlin.collections.List<kotlin.String>? = null,

    /* HA resources, which will be migrated to the same target node as the VM, because these are in positive affinity with the VM. */
    @Json(name = "dependent-ha-resources")
    val dependentHaResources: kotlin.collections.List<kotlin.String>? = null,

    /* Whether the VM host supports migrating additional VM state, such as conntrack entries. */
    @Json(name = "has-dbus-vmstate")
    val hasDbusVmstate: kotlin.Boolean? = false,

    @Json(name = "not_allowed_nodes")
    val notAllowedNodes: PveRemotesGetMigrateResponseDataNotAllowedNodes? = null

) {


}

