/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models

import com.clientapi.pdm.models.PdmPveRemotesTypeEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id FIXME: Missing description in PVE.
 * @param name FIXME: Missing description in PVE.
 * @param type Indicates the type, either cluster or node. The type defines the object properties e.g. quorate available for type cluster.
 * @param ip [node] IP of the resolved nodename.
 * @param level [node] Proxmox VE Subscription level, indicates if eligible for enterprise support as well as access to the stable Proxmox VE Enterprise Repository.
 * @param local [node] Indicates if this is the responding node.
 * @param nodeid [node] ID of the node from the corosync configuration.
 * @param nodes [cluster] Nodes count, including offline nodes.
 * @param online [node] Indicates if the node is online or offline.
 * @param quorate [cluster] Indicates if there is a majority of nodes online to make decisions
 * @param version [cluster] Current version of the corosync configuration file.
 */


data class PveRemotesGetClusterStatusResponseDataInner (

    /* FIXME: Missing description in PVE. */
    @Json(name = "id")
    val id: kotlin.String,

    /* FIXME: Missing description in PVE. */
    @Json(name = "name")
    val name: kotlin.String,

    /* Indicates the type, either cluster or node. The type defines the object properties e.g. quorate available for type cluster. */
    @Json(name = "type")
    val type: PdmPveRemotesTypeEnum,

    /* [node] IP of the resolved nodename. */
    @Json(name = "ip")
    val ip: kotlin.String? = null,

    /* [node] Proxmox VE Subscription level, indicates if eligible for enterprise support as well as access to the stable Proxmox VE Enterprise Repository. */
    @Json(name = "level")
    val level: kotlin.String? = null,

    /* [node] Indicates if this is the responding node. */
    @Json(name = "local")
    val local: kotlin.Boolean? = false,

    /* [node] ID of the node from the corosync configuration. */
    @Json(name = "nodeid")
    val nodeid: kotlin.Long? = null,

    /* [cluster] Nodes count, including offline nodes. */
    @Json(name = "nodes")
    val nodes: kotlin.Long? = null,

    /* [node] Indicates if the node is online or offline. */
    @Json(name = "online")
    val online: kotlin.Boolean? = false,

    /* [cluster] Indicates if there is a majority of nodes online to make decisions */
    @Json(name = "quorate")
    val quorate: kotlin.Boolean? = false,

    /* [cluster] Current version of the corosync configuration file. */
    @Json(name = "version")
    val version: kotlin.Long? = null

) {


}

