/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models

import com.clientapi.pdm.models.PdmPveRemotesMigrationTypeEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param target Node name (or 'localhost')
 * @param bwlimit Override I/O bandwidth limit (in KiB/s).
 * @param force Allow to migrate VMs with local devices.
 * @param migrationNetwork CIDR of the (sub) network that is used for migration.
 * @param migrationType Migration traffic is encrypted using an SSH tunnel by default. On secure, completely private networks this can be disabled to increase performance.
 * @param node Node name (or 'localhost')
 * @param online Perform an online migration if the vm is running.
 * @param targetStorage List of storage mappings
 * @param withLocalDisks Enable live storage migration for local disks.
 */


data class PveRemotesCreatePveRemotesByRemoteQemuByVmidMigrateRequest (

    /* Node name (or 'localhost') */
    @Json(name = "target")
    val target: kotlin.String,

    /* Override I/O bandwidth limit (in KiB/s). */
    @Json(name = "bwlimit")
    val bwlimit: kotlin.Long? = null,

    /* Allow to migrate VMs with local devices. */
    @Json(name = "force")
    val force: kotlin.Boolean? = 0,

    /* CIDR of the (sub) network that is used for migration. */
    @Json(name = "migration-network")
    val migrationNetwork: kotlin.String? = null,

    /* Migration traffic is encrypted using an SSH tunnel by default. On secure, completely private networks this can be disabled to increase performance. */
    @Json(name = "migration-type")
    val migrationType: PdmPveRemotesMigrationTypeEnum? = null,

    /* Node name (or 'localhost') */
    @Json(name = "node")
    val node: kotlin.String? = null,

    /* Perform an online migration if the vm is running. */
    @Json(name = "online")
    val online: kotlin.Boolean? = null,

    /* List of storage mappings */
    @Json(name = "target-storage")
    val targetStorage: kotlin.collections.List<kotlin.String>? = null,

    /* Enable live storage migration for local disks. */
    @Json(name = "with-local-disks")
    val withLocalDisks: kotlin.Boolean? = null

) {


}

