/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param target Remote ID.
 * @param targetBridge List of bridge mappings
 * @param targetStorage List of storage mappings
 * @param bwlimit Override I/O bandwidth limit (in KiB/s).
 * @param delete Delete the original VM and related data after successful migration.
 * @param node Node name (or 'localhost')
 * @param online Perform an online migration if the vm is running.
 * @param targetEndpoint The target endpoint to use for the connection.
 * @param targetVmid A guest ID
 */


data class PveRemotesCreatePveRemotesByRemoteQemuByVmidRemoteMigrateRequest (

    /* Remote ID. */
    @Json(name = "target")
    val target: kotlin.String,

    /* List of bridge mappings */
    @Json(name = "target-bridge")
    val targetBridge: kotlin.collections.List<kotlin.String>,

    /* List of storage mappings */
    @Json(name = "target-storage")
    val targetStorage: kotlin.collections.List<kotlin.String>,

    /* Override I/O bandwidth limit (in KiB/s). */
    @Json(name = "bwlimit")
    val bwlimit: kotlin.Long? = null,

    /* Delete the original VM and related data after successful migration. */
    @Json(name = "delete")
    val delete: kotlin.Boolean? = false,

    /* Node name (or 'localhost') */
    @Json(name = "node")
    val node: kotlin.String? = null,

    /* Perform an online migration if the vm is running. */
    @Json(name = "online")
    val online: kotlin.Boolean? = false,

    /* The target endpoint to use for the connection. */
    @Json(name = "target-endpoint")
    val targetEndpoint: kotlin.String? = null,

    /* A guest ID */
    @Json(name = "target-vmid")
    val targetVmid: kotlin.Long? = null

) {


}

