/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models

import com.clientapi.pdm.models.PdmContentField
import com.clientapi.pdm.models.PveRemotesGetStorageResponseDataInnerFormats

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param content Allowed storage content types.
 * @param storage The storage identifier.
 * @param type Storage type.
 * @param active Set when storage is accessible.
 * @param avail Available storage space in bytes.
 * @param enabled Set when storage is enabled (not disabled).
 * @param formats 
 * @param selectExisting Instead of creating new volumes, one must select one that is already existing. Only included if 'format' parameter is set.
 * @param shared Shared flag from storage configuration.
 * @param total Total storage space in bytes.
 * @param used Used storage space in bytes.
 * @param usedFraction Used fraction (used/total).
 */


data class PveRemotesGetStorageResponseDataInner (

    /* Allowed storage content types. */
    @Json(name = "content")
    val content: PdmContentField,

    /* The storage identifier. */
    @Json(name = "storage")
    val storage: kotlin.String,

    /* Storage type. */
    @Json(name = "type")
    val type: kotlin.String,

    /* Set when storage is accessible. */
    @Json(name = "active")
    val active: kotlin.Boolean? = false,

    /* Available storage space in bytes. */
    @Json(name = "avail")
    val avail: kotlin.Long? = null,

    /* Set when storage is enabled (not disabled). */
    @Json(name = "enabled")
    val enabled: kotlin.Boolean? = false,

    @Json(name = "formats")
    val formats: PveRemotesGetStorageResponseDataInnerFormats? = null,

    /* Instead of creating new volumes, one must select one that is already existing. Only included if 'format' parameter is set. */
    @Json(name = "select_existing")
    val selectExisting: kotlin.Boolean? = false,

    /* Shared flag from storage configuration. */
    @Json(name = "shared")
    val shared: kotlin.Boolean? = false,

    /* Total storage space in bytes. */
    @Json(name = "total")
    val total: kotlin.Long? = null,

    /* Used storage space in bytes. */
    @Json(name = "used")
    val used: kotlin.Long? = null,

    /* Used fraction (used/total). */
    @Json(name = "used_fraction")
    val usedFraction: java.math.BigDecimal? = null

) {


}

