/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models

import com.clientapi.pdm.models.PdmContentField

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param content Allowed storage content types.
 * @param type Storage type.
 * @param active Set when storage is accessible.
 * @param avail Available storage space in bytes.
 * @param enabled Set when storage is enabled (not disabled).
 * @param shared Shared flag from storage configuration.
 * @param total Total storage space in bytes.
 * @param used Used storage space in bytes.
 */


data class PveRemotesGetPveRemotesByRemoteNodesByNodeStorageByStorageStatusResponseData (

    /* Allowed storage content types. */
    @Json(name = "content")
    val content: PdmContentField,

    /* Storage type. */
    @Json(name = "type")
    val type: kotlin.String,

    /* Set when storage is accessible. */
    @Json(name = "active")
    val active: kotlin.Boolean? = 0,

    /* Available storage space in bytes. */
    @Json(name = "avail")
    val avail: kotlin.Long? = null,

    /* Set when storage is enabled (not disabled). */
    @Json(name = "enabled")
    val enabled: kotlin.Boolean? = 0,

    /* Shared flag from storage configuration. */
    @Json(name = "shared")
    val shared: kotlin.Boolean? = 0,

    /* Total storage space in bytes. */
    @Json(name = "total")
    val total: kotlin.Long? = null,

    /* Used storage space in bytes. */
    @Json(name = "used")
    val used: kotlin.Long? = null

) {


}

