/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id The task id.
 * @param node The task's node.
 * @param pid The task process id.
 * @param pstart The task's proc start time.
 * @param starttime The task's start time.
 * @param type The task type.
 * @param upid The task's UPID.
 * @param user The task owner's user id.
 * @param endtime The task's end time.
 * @param status The task's status.
 */


data class PveRemotesGetTasksResponseDataInner (

    /* The task id. */
    @Json(name = "id")
    val id: kotlin.String,

    /* The task's node. */
    @Json(name = "node")
    val node: kotlin.String,

    /* The task process id. */
    @Json(name = "pid")
    val pid: kotlin.Long,

    /* The task's proc start time. */
    @Json(name = "pstart")
    val pstart: kotlin.Long,

    /* The task's start time. */
    @Json(name = "starttime")
    val starttime: kotlin.Long,

    /* The task type. */
    @Json(name = "type")
    val type: kotlin.String,

    /* The task's UPID. */
    @Json(name = "upid")
    val upid: kotlin.String,

    /* The task owner's user id. */
    @Json(name = "user")
    val user: kotlin.String,

    /* The task's end time. */
    @Json(name = "endtime")
    val endtime: kotlin.Long? = null,

    /* The task's status. */
    @Json(name = "status")
    val status: kotlin.String? = null

) {


}

