/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param time Timestamp (UNIX epoch)
 * @param cpuAvg1 CPU utilization, averaged over the last minute
 * @param cpuAvg15 CPU utilization, averaged over the last fifteen minutes
 * @param cpuAvg5 CPU utilization, averaged over the last five minutes
 * @param cpuCurrent Current CPU utilization
 * @param cpuIowait Current IO wait
 * @param cpuMax Max CPU utiliziation (Number of cores)
 * @param diskTotal Total disk size
 * @param diskUsed Disk utiliziation
 * @param memTotal Total memory size
 * @param memUsed Currently used memory
 * @param netIn Inbound network data rate
 * @param netOut Outboud network data rate
 * @param swapTotal Total swap size
 * @param swapUsed Currently used swap
 * @param uptime Container uptime
 */


data class PveRemotesGetPveRemotesByRemoteNodesByNodeRrddataResponseDataInner (

    /* Timestamp (UNIX epoch) */
    @Json(name = "time")
    val time: kotlin.Long,

    /* CPU utilization, averaged over the last minute */
    @Json(name = "cpu-avg1")
    val cpuAvg1: java.math.BigDecimal? = null,

    /* CPU utilization, averaged over the last fifteen minutes */
    @Json(name = "cpu-avg15")
    val cpuAvg15: java.math.BigDecimal? = null,

    /* CPU utilization, averaged over the last five minutes */
    @Json(name = "cpu-avg5")
    val cpuAvg5: java.math.BigDecimal? = null,

    /* Current CPU utilization */
    @Json(name = "cpu-current")
    val cpuCurrent: java.math.BigDecimal? = null,

    /* Current IO wait */
    @Json(name = "cpu-iowait")
    val cpuIowait: java.math.BigDecimal? = null,

    /* Max CPU utiliziation (Number of cores) */
    @Json(name = "cpu-max")
    val cpuMax: java.math.BigDecimal? = null,

    /* Total disk size */
    @Json(name = "disk-total")
    val diskTotal: java.math.BigDecimal? = null,

    /* Disk utiliziation */
    @Json(name = "disk-used")
    val diskUsed: java.math.BigDecimal? = null,

    /* Total memory size */
    @Json(name = "mem-total")
    val memTotal: java.math.BigDecimal? = null,

    /* Currently used memory */
    @Json(name = "mem-used")
    val memUsed: java.math.BigDecimal? = null,

    /* Inbound network data rate */
    @Json(name = "net-in")
    val netIn: java.math.BigDecimal? = null,

    /* Outboud network data rate */
    @Json(name = "net-out")
    val netOut: java.math.BigDecimal? = null,

    /* Total swap size */
    @Json(name = "swap-total")
    val swapTotal: java.math.BigDecimal? = null,

    /* Currently used swap */
    @Json(name = "swap-used")
    val swapUsed: java.math.BigDecimal? = null,

    /* Container uptime */
    @Json(name = "uptime")
    val uptime: java.math.BigDecimal? = null

) {


}

