/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models

import com.clientapi.pdm.models.PdmRemotesRemoteInlineEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param authid Authentication ID
 * @param delete List of properties to delete.
 * @param digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
 * @param nodes A list of cluster node addresses.
 * @param token The access token's secret.
 * @param webUrl Configuration for the Web UI URL link generation.
 */


data class RemotesRemoteUpdateRemoteRequest (

    /* Authentication ID */
    @Json(name = "authid")
    val authid: kotlin.String? = null,

    /* List of properties to delete. */
    @Json(name = "delete")
    val delete: kotlin.collections.List<PdmRemotesRemoteInlineEnum>? = null,

    /* Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications. */
    @Json(name = "digest")
    val digest: kotlin.String? = null,

    /* A list of cluster node addresses. */
    @Json(name = "nodes")
    val nodes: kotlin.collections.List<kotlin.String>? = null,

    /* The access token's secret. */
    @Json(name = "token")
    val token: kotlin.String? = null,

    /* Configuration for the Web UI URL link generation. */
    @Json(name = "web-url")
    val webUrl: kotlin.String? = null

) {


}

