/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param byRemote A map of remotes to status counts
 * @param byType A map of worker-types to status counts
 */


data class RemotesTasksGetStatisticsResponseData (

    /* A map of remotes to status counts */
    @Json(name = "by-remote")
    val byRemote: kotlin.Any,

    /* A map of worker-types to status counts */
    @Json(name = "by-type")
    val byType: kotlin.Any

) {


}

