/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models

import com.clientapi.pdm.models.ResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param remote The remote the resource is on
 * @param resource 
 * @param rrdData 
 */


data class ResourcesGetTopEntitiesResponseDataGuestCpuInner (

    /* The remote the resource is on */
    @Json(name = "remote")
    val remote: kotlin.String,

    @Json(name = "resource")
    val resource: kotlin.Any,

    @Json(name = "rrd-data")
    val rrdData: ResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData

) {


}

