/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param remote Remote ID.
 * @param resources Array of resources found at this remote.
 * @param error Any error that occurred when querying remote resources
 */


data class ResourcesGetListResponseDataInner (

    /* Remote ID. */
    @Json(name = "remote")
    val remote: kotlin.String,

    /* Array of resources found at this remote. */
    @Json(name = "resources")
    val resources: kotlin.collections.List<kotlin.Any>,

    /* Any error that occurred when querying remote resources */
    @Json(name = "error")
    val error: kotlin.String? = null

) {


}

