/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models

import com.clientapi.pdm.models.ResourcesGetTopEntitiesResponseDataGuestCpuInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param guestCpu The top entries for Guest CPU
 * @param nodeCpu The top entries for Node CPU
 * @param nodeMemory The top entries for Node Memory
 */


data class ResourcesGetTopEntitiesResponseData (

    /* The top entries for Guest CPU */
    @Json(name = "guest-cpu")
    val guestCpu: kotlin.collections.List<ResourcesGetTopEntitiesResponseDataGuestCpuInner>,

    /* The top entries for Node CPU */
    @Json(name = "node-cpu")
    val nodeCpu: kotlin.collections.List<ResourcesGetTopEntitiesResponseDataGuestCpuInner>,

    /* The top entries for Node Memory */
    @Json(name = "node-memory")
    val nodeMemory: kotlin.collections.List<ResourcesGetTopEntitiesResponseDataGuestCpuInner>

) {


}

