/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pdm.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param remote Remote ID.
 * @param zone The name for an SDN object (zone / vnet / fabric).
 */


data class SdnVnetsCreateVnetsRequestRemotesInner (

    /* Remote ID. */
    @Json(name = "remote")
    val remote: kotlin.String,

    /* The name for an SDN object (zone / vnet / fabric). */
    @Json(name = "zone")
    val zone: kotlin.String

) {


}

